using Polymorfa.Sdk;

internal static class AccountTests
{
    public static async Task RunAsync()
    {
        await Organization("GET", "/platform/team", null, """{"data":{"id":"o1","externalId":"external1","name":"Team","slug":null,"email":"owner@example.com","timezone":null,"creditBalanceCents":1234,"lowBalanceThresholdCents":100,"billingEmail":null,"status":"active","plan":"free","planStatus":null,"isActive":true,"createdAt":10,"updatedAt":20}}""", async c => ResourceTests.Equal((await c.Organizations.RetrieveAsync()).Data.Data.CreditBalanceCents, 1234L));
        await Organization("GET", "/platform/members", null, """{"data":[{"_id":"m1","_creationTime":10,"orgId":"o1","userId":"u1","email":"owner@example.com","name":null,"role":"owner","status":"active","invitedAt":null,"joinedAt":20}]}""", async c => ResourceTests.Equal((await c.Members.ListAsync()).Data.Data[0].Role, "owner"));
        await Organization("GET", "/platform/keys", null, """{"data":[{"_id":"k1","_creationTime":10,"id":"k1","keyId":"key1","start":"pmfa_","last4":"ABCD","orgId":"o1","label":"CI","scopes":123,"source":"console","expiresAt":100,"isActive":false,"lastUsed":null}]}""", async c => ResourceTests.True(!(await c.ApiKeys.ListAsync()).Data.Data[0].IsActive));
        await Organization("DELETE", "/platform/keys/key1", null, """{"data":{"ok":true,"keyId":"key1"}}""", async c => ResourceTests.True((await c.ApiKeys.DeactivateAsync("key1")).Data.Data.Ok));
        await Organization("GET", "/platform/tokens?projectId=p1", null, """{"data":[{"id":"pt1","start":"pmfa_pt_","last4":"ABCD","label":null,"scopes":123,"expiresAt":null,"createdAt":10,"lastUsedAt":null,"revokedAt":20}]}""", async c => ResourceTests.Equal((await c.ProjectTokens.ListAsync("p1")).Data.Data[0].RevokedAt, 20L));
        await Organization("GET", "/platform/audit?action=session.stop&resource=number&limit=2", null, """{"data":[{"id":"a1","actorEmail":"owner@example.com","actorUserId":null,"actorRole":"owner","action":"session.stop","resource":"number","projectId":"p1","projectName":"Support","ip":null,"userAgent":null,"duration":12,"source":"api","description":null,"result":"success","metadata":{"accepted":true},"createdAt":20}]}""", async c => ResourceTests.True((await c.AuditLogs.ListAsync(new("session.stop", "number", 2))).Data.Data[0].Metadata.GetProperty("accepted").GetBoolean()));
        await Organization("GET", "/platform/incidents", null, """{"data":[{"id":"i1","keyId":"key1","tokenType":"organization","source":"scan","url":null,"ref":null,"resolution":"revoked","detectedAt":10,"acknowledgedAt":null,"acknowledgedBy":null,"createdAt":10}]}""", async c => ResourceTests.Equal((await c.SecurityIncidents.ListAsync()).Data.Data[0].Resolution, "revoked"));
        await Organization("POST", "/platform/incidents/i1/acknowledge", null, """{"data":{"acknowledged":true}}""", async c => ResourceTests.True((await c.SecurityIncidents.AcknowledgeAsync("i1")).Data.Data.Acknowledged));
        await Organization("GET", "/platform/bans", null, """{"data":[{"id":"b1","sessionName":"support","banCode":401,"banReason":"temporary","banExpiresAt":null,"occurredAt":10,"status":"active"}]}""", async c => ResourceTests.Equal((await c.SessionBans.ListAsync()).Data.Data[0].BanCode, 401));
        await Organization("GET", "/platform/bans/active", null, """{"data":[{"id":"b1","sessionName":"support","banCode":401,"banReason":"temporary","banExpiresAt":null,"occurredAt":10,"status":"active"}]}""", async c => ResourceTests.Equal((await c.SessionBans.ListActiveAsync()).Data.Data[0].SessionName, "support"));
        await Messaging("POST", "/platform/client-tokens", """{"ephemeralId":"visitor1","customer":"cu1","allow":["n1"],"ttlSeconds":600}""", """{"success":true,"data":{"token":"pmfa_ct_once","expiresAt":"2026-09-22T00:10:00Z"}}""", async c => { var token = (await c.ClientTokens.MintAsync(new("visitor1", Customer: "cu1", Allow: ["n1"], TtlSeconds: 600))).Data.Data; ResourceTests.Equal(token.Token, "pmfa_ct_once"); ResourceTests.True(!token.ToString().Contains("pmfa_ct_once")); });
        await Messaging("GET", "/platform/sessions/support/client-rules", null, """{"success":true,"data":{"recipientMode":"all","allowedActions":"send","rateLimit":10,"maxDaily":100,"allowedOrigins":"https://customer.example","conversationTtlSeconds":600,"maxConcurrency":1,"maxSetupsPerMinute":5,"allowedNumber":"+15550001111","enabled":false}}""", async c => ResourceTests.Equal((await c.ClientTokens.RetrieveRulesAsync("support")).Data.Data.MaxSetupsPerMinute, 5));
        await Messaging("PUT", "/platform/sessions/support/client-rules", """{"recipientMode":"all","enabled":false,"rateLimit":0}""", """{"success":true}""", async c => ResourceTests.True((await c.ClientTokens.UpdateRulesAsync("support", new("all", false, RateLimit: 0))).Data.Success));
        await Messaging("DELETE", "/platform/sessions/support/client-rules", null, """{"success":true}""", async c => ResourceTests.True((await c.ClientTokens.DeleteRulesAsync("support")).Data.Success));
        await Messaging("GET", "/messaging/support/identities/resolve?username=Zo%C3%AB&usernameKey=key1", null, """{"success":true,"data":{"id":"lid1","bsuid":"US.123","phoneNumber":"+15550001111","username":"Zoë","keyRequired":false}}""", async c => ResourceTests.Equal((await c.Identities.ResolveAsync("support", new(Username: "Zoë", UsernameKey: "key1"))).Data.Data.KeyRequired, false));
        await Messaging("POST", "/messaging/support/messages/seen", """{"conversation":{"id":"peer"},"id":"m1"}""", """{"success":true,"data":{"status":"OK"}}""", async c => ResourceTests.Equal((await c.Messages.MarkSeenAsync("support", new(new(Id: "peer"), "m1"))).Data.Data.Status, "OK"));
        await Messaging("POST", "/messaging/support/messages/typing", """{"conversation":{"id":"peer"},"state":"composing"}""", """{"success":true,"data":{"status":"OK"}}""", async c => ResourceTests.Equal((await c.Messages.SetTypingAsync("support", new(new(Id: "peer"), "composing"))).Data.Data.Status, "OK"));
        await Messaging("POST", "/messaging/support/messages/react", """{"conversation":{"id":"peer"},"id":"m1","reaction":"🐈","transport":"official_api"}""", """{"success":true,"data":{"id":"r1","whatsapp_ids":{"official_api":"wa1"},"whatsapp_id":"wa1","conversation":{"id":"peer"},"timestamp":"2026-09-22T00:00:00Z","status":"pending","transport":"official_api","routingReason":"cloud_preferred","operationId":"op1"}}""", async c => { var r = (await c.Messages.ReactAsync("support", new(new(Id: "peer"), "m1", "🐈", "official_api"))).Data.Data; ResourceTests.Equal(r.WhatsAppId, "wa1"); ResourceTests.Equal(r.OperationId, "op1"); });
        await Messaging("POST", "/messaging/support/messages/star", """{"conversation":{"id":"peer"},"id":"m1","star":false}""", """{"success":true,"data":{"status":"OK"}}""", async c => ResourceTests.Equal((await c.Messages.StarAsync("support", new(new(Id: "peer"), "m1", false))).Data.Data.Status, "OK"));
        await Messaging("GET", "/messaging/support/operations/op1", null, """{"success":true,"data":{"operationId":"op1","status":"unknown","transport":"official_api","rejectionCode":null,"receipt":null}}""", async c => ResourceTests.Equal((await c.Messages.OperationStatusAsync("support", "op1")).Data.Data.Status, "unknown"));
        using var client = new MessagingClient(Credential.ClientToken("pmfa_ct_fixture"));
        try { await client.ClientTokens.MintAsync(new("visitor1", Session: "support")); throw new Exception("Client minted server token"); } catch (PolymorfaConfigurationException) { }
        using var server = new MessagingClient(Credential.OrganizationApiKey("pmfa_" + new string('a', 72)));
        try { await server.ClientTokens.MintAsync(new("visitor1", Session: "support", Customer: "cu1")); throw new Exception("Conflicting targets accepted"); } catch (PolymorfaConfigurationException) { }
        Console.WriteLine("PASS typed account metadata, security, client token rules, identity and message controls");
    }
    private static Task Organization(string method, string path, string? body, string response, Func<OrganizationClient, Task> invoke) => BillingTests.Organization(method, path, body, response, invoke);
    private static Task Messaging(string method, string path, string? body, string response, Func<MessagingClient, Task> invoke) => ResourceTests.Messaging(method, path, body, response, invoke);
}
