using System.Text.Json;
using Polymorfa.Sdk;

internal static class AudienceSettingsTests
{
    private const string Id = "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee";
    public static async Task RunAsync()
    {
        await Organization("GET", "/platform/audiences", null, """{"data":{"items":[],"future":"kept"}}""", async c => ResourceTests.Equal((await c.Audiences.ListAsync()).Data.Data["future"].GetString(), "kept"));
        await Organization("POST", "/platform/audiences", """{"name":"Customers","source":"api","members":[{"phone":"+15550001111","variables":{"active":false,"price":1.123456}}]}""", """{"data":{"id":"a1","name":"Customers","source":"api","recipientCount":1,"fileId":null,"columns":null,"sampleRow":null,"mapping":null,"createdAt":9007199254740993,"updatedAt":42,"duplicateCount":1,"invalidCount":1,"invalidRows":[{"row":3,"reason":"invalid_phone"}]}}""", async c => ResourceTests.Equal((await c.Audiences.CreateAsync(CreateAudienceRequest.FromMembers("Customers", [new("+15550001111", new Dictionary<string, JsonElement> { ["active"] = JsonSerializer.SerializeToElement(false), ["price"] = JsonSerializer.SerializeToElement(1.123456m) })], "api"))).Data.Data.CreatedAt, 9007199254740993L));
        await Organization("GET", "/platform/audiences/a1", null, """{"data":{"name":"Customers"}}""", async c => ResourceTests.Equal((await c.Audiences.RetrieveAsync("a1")).Data.Data["name"].GetString(), "Customers"));
        await Organization("DELETE", "/platform/audiences/a1", null, """{"data":{"deleted":true}}""", async c => ResourceTests.True((await c.Audiences.DeleteAsync("a1")).Data.Data["deleted"].GetBoolean()));
        await Organization("POST", "/platform/audiences/uploads", null, """{"data":{"uploadId":"upload1"}}""", async c => ResourceTests.Equal((await c.Audiences.CreateUploadAsync()).Data.Data["uploadId"].GetString(), "upload1"));
        await Organization("POST", "/platform/audiences/a1/members", """{"members":[{"phone":"+15550001111"}]}""", """{"data":{"listId":"a1","added":1,"recipientCount":2,"duplicateCount":0,"invalidCount":1,"invalidRows":[{"row":2,"reason":"invalid_variables"}]}}""", async c => ResourceTests.Equal((await c.Audiences.AddMembersAsync("a1", new([new("+15550001111")]))).Data.Data.InvalidRows[0].Reason, "invalid_variables"));
        await Organization("GET", "/platform/audiences/a1/members?cursor=c1&limit=25", null, """{"data":[{"id":"m1","phone":"+15550001111","variables":{"price":"1.123456"},"createdAt":42}],"page":{"nextCursor":null}}""", async c => ResourceTests.Equal((await c.Audiences.ListMembersAsync("a1", new("c1", 25))).Items[0].Variables["price"], "1.123456"));
        await Organization("DELETE", "/platform/audiences/a1/members/%2B15550001111", null, """{"data":{"removed":true,"listId":"a1","phone":"+15550001111","recipientCount":1}}""", async c => ResourceTests.True((await c.Audiences.DeleteMemberAsync("a1", "+15550001111")).Data.Data.Removed));
        await Organization("GET", "/platform/quicklink?projectId=" + Id, null, """{"data":null}""", async c => ResourceTests.Equal((await c.Project(Id).QuickLinkSettings.RetrieveAsync()).Data, null));
        await Organization("PUT", "/platform/quicklink", "{\"enabled\":false,\"successCallbackUrl\":null,\"radiusPx\":0,\"methods\":[],\"projectId\":\"" + Id + "\"}", "{\"data\":{\"id\":\"q1\",\"projectId\":\"" + Id + "\",\"enabled\":false,\"successCallbackUrl\":null,\"failureCallbackUrl\":null,\"businessName\":null,\"headline\":null,\"description\":null,\"successMessage\":null,\"supportUrl\":null,\"privacyUrl\":null,\"termsUrl\":null,\"accent\":null,\"theme\":\"system\",\"hideWatermark\":false,\"allowPhoneChange\":false,\"shape\":null,\"radiusPx\":0,\"logoMode\":\"project\",\"logoStorageId\":null,\"logoSourceStorageId\":null,\"logoUrl\":null,\"historySync\":\"ask\",\"methods\":[],\"defaultMethod\":null,\"createdAt\":42,\"updatedAt\":43}}", async c => ResourceTests.Equal((await c.Project(Id).QuickLinkSettings.UpdateAsync(new() { Enabled = false, SuccessCallbackUrl = PatchValue<string>.Set(null), RadiusPx = PatchValue<decimal?>.Set(0), Methods = PatchValue<IReadOnlyList<string>>.Set([]) })).Data.RadiusPx, 0m));
        var fromFile = JsonSerializer.Serialize(CreateAudienceRequest.FromFile("Imported", "file1", new("Phone", new Dictionary<string, string> { ["name"] = "Name" })), new JsonSerializerOptions { PropertyNamingPolicy = JsonNamingPolicy.CamelCase, DefaultIgnoreCondition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull }); ResourceTests.True(!fromFile.Contains("members") && fromFile.Contains("mapping"));
        Console.WriteLine("PASS audience imports/member cursors and nullable bound QuickLink settings");
    }
    private static Task Organization(string method, string path, string? body, string response, Func<OrganizationClient, Task> invoke) => BillingTests.Organization(method, path, body, response, invoke);
}
