using Polymorfa.Sdk;
using System.Text.Json;

internal static class BanSafeTests
{
    private const string Health = """{"sessionId":"s1","session":"support","phoneNumber":"+15550001111","projectId":"p1","health":null,"band":"unknown","healthSource":"unavailable","healthEstimatorVersion":null,"healthModelVersion":null,"healthEvaluatedAt":null,"healthFeatureCoverage":null,"healthReliability":"unavailable","healthUnavailableReason":"no_active_model","healthProbabilities":null,"mostLikelyHealthState":null,"healthExplanation":null,"observedAccountState":{"state":"limited","observedAt":"2026-09-22","source":"restriction_event"},"enforcement":null}""";
    private const string Incident = """{"id":"i1","sessionId":"s1","session":"support","phoneNumber":"+15550001111","projectId":"p1","kind":"customer_report","source":"customer","resolution":"retracted","ambiguous":true,"startedAt":"2026-09-22","endsAt":null,"closedAt":null,"closedBy":"owner","claimId":null,"note":null,"reportedBy":null,"createdAt":"2026-09-22"}""";
    private const string Claim = """{"id":"c1","incidentId":"i1","sessionId":"s1","session":"support","phoneNumber":"+15550001111","projectId":"p1","status":"paid","verdict":"ours","windowStart":"2026-09-01","windowEnd":"2026-09-22","measuredCents":1.123456,"capCents":2.123456,"amountCents":0.123456,"evidence":{"attributionRuleVersion":1,"windowDays":21,"deviceEvidence":false,"otherDevices":0,"restrictedInWindow":false,"criticalFindingDays":0,"sharedConnection":false,"measuredHours":1.5},"summary":"Reviewed","reason":"ours","decidedAt":null,"paidAt":null,"createdAt":"2026-09-22"}""";
    private const string Collection = """{"state":"fresh","latestFlushedAt":"2026-09-22","latestReceivedAt":"2026-09-22","freshUntil":null,"recordVersion":1,"collectorVersion":1,"partial":false,"droppedRecords":0}""";
    private const string Snapshot = """{"bucketStart":"2026-09-22","flushedAt":"2026-09-22","receivedAt":"2026-09-22","partial":false,"recordVersion":1,"signals":[{"key":"latency","label":"Latency","group":"delivery","kind":"histogram","unit":"milliseconds","description":"Latency","measured":true,"value":[1.25,2.5],"sampleSize":2,"codes":null},{"key":"ready","label":"Ready","group":"connection","kind":"boolean","unit":"none","description":"Ready","measured":true,"value":false,"sampleSize":0,"codes":[{"code":403,"count":1}]}]}""";
    public static async Task RunAsync()
    {
        await Organization("GET", "/platform/bansafe/health?projectId=p1&limit=2", null, Page(Health), async c => ResourceTests.Equal((await c.BanSafe.ListHealthAsync(new(ProjectId: "p1", Limit: 2))).Items[0].ObservedAccountState!.State, "limited"));
        var detail = Health[..^1] + """, "warmup":{"enabled":true,"tenureSource":"history","tenureDay":1,"allowance":20,"sentToday":0,"resetsAt":null,"curve":[{"day":1,"allowance":20}]},"findings":[],"liftRequires":null,"appealState":"none"}""";
        await Organization("GET", "/platform/bansafe/health/support", null, Envelope(detail), async c => ResourceTests.Equal((await c.BanSafe.GetHealthAsync("support")).Data.Data.Warmup.Curve[0].Allowance, 20));
        await Organization("GET", "/platform/bansafe/health/support/history?since=2026-09-01&limit=3", null, "{\"data\":{\"sessionId\":\"s1\",\"session\":\"support\",\"points\":[" + Health + "]}}", async c => ResourceTests.Equal((await c.BanSafe.ListHealthHistoryAsync("support", new("2026-09-01", 3))).Data.Data.Points[0].Health, null));
        await Organization("GET", "/platform/bansafe/signals", null, """{"data":[{"key":"latency","label":"Latency","group":"delivery","kind":"histogram","unit":"milliseconds","description":"Latency"}]}""", async c => ResourceTests.Equal((await c.BanSafe.ListSignalsAsync()).Data.Data[0].Kind, "histogram"));
        await Organization("GET", "/platform/bansafe/telemetry/support", null, "{\"data\":{\"sessionId\":\"s1\",\"session\":\"support\",\"projectId\":\"p1\",\"collection\":" + Collection + ",\"snapshot\":" + Snapshot + "}}", async c => ResourceTests.Equal(((BanSafeHistogramSignal)(await c.BanSafe.GetTelemetryAsync("support")).Data.Data.Snapshot!.Signals[0].Value!).Values[0], 1.25m));
        await Organization("GET", "/platform/bansafe/telemetry/support/history?since=a&until=b&cursor=older&limit=2", null, Page(Snapshot), async c => ResourceTests.True(!((BanSafeBooleanSignal)(await c.BanSafe.ListTelemetryHistoryAsync("support", new("a", "b", "older", 2))).Items[0].Signals[1].Value!).Value));
        await Organization("GET", "/platform/bansafe/collection?projectId=p1", null, Page("{\"sessionId\":\"s1\",\"session\":\"support\",\"projectId\":\"p1\",\"collection\":" + Collection + "}"), async c => ResourceTests.Equal((await c.BanSafe.ListCollectionAsync(new("p1"))).Items[0].Collection.Partial, false));
        await Organization("GET", "/platform/bansafe/health-actions?session=support&status=pending", null, Page("""{"id":"a1","sessionId":"s1","session":"support","projectId":"p1","mode":"apply","action":"slow_down","status":"pending","health":0.5,"threshold":0.6,"healthSource":"ml_model","estimatorVersion":"v1","modelVersion":null,"slowDownMps":0.123456,"evaluatedAt":"2026-09-22","createdAt":"2026-09-22","completedAt":null,"outcome":null}"""), async c => ResourceTests.Equal((await c.BanSafe.ListHealthActionsAsync(new(Session: "support", Status: "pending"))).Items[0].SlowDownMps, 0.123456m));
        await Organization("GET", "/platform/bansafe/findings?session=support&status=open&severity=warning", null, Page("""{"id":null,"key":"latency","title":"Latency","summary":"Observed","fix":"Wait","status":"open","severity":"warning","occurrences":1,"reopenedCount":0,"evidence":{"ratio":0.25},"sessionId":"s1","session":"support","phoneNumber":"+15550001111","firstSeenAt":null,"lastSeenAt":null,"acknowledgedAt":null,"acknowledgedBy":null,"acknowledgementNote":null,"snoozedUntil":null,"resolvedAt":null,"resolveReason":null}"""), async c => ResourceTests.Equal((await c.BanSafe.ListFindingsAsync(new(Session: "support", Status: "open", Severity: "warning"))).Items[0].Evidence["ratio"], 0.25m));
        await Organization("GET", "/platform/bansafe/enforcement?rung=throttle", null, Page(Health[..^1] + """, "rung":"throttle","previousRung":"notify","organizationFloor":"none","reason":"conduct","source":"automatic","throughputPerMinute":1.5,"blocksUnsolicited":true,"suspended":false,"blockingFindings":[],"startedAt":"2026-09-22","eligibleLiftAt":null,"liftRequires":"wait","operatorHold":false,"appealState":"none","state":"applying"}"""), async c => ResourceTests.True((await c.BanSafe.ListEnforcementAsync(new(Rung: "throttle"))).Items[0].BlocksUnsolicited));
        await Organization("GET", "/platform/bansafe/incidents?session=support", null, Page(Incident), async c => ResourceTests.True((await c.BanSafe.ListIncidentsAsync(new(Session: "support"))).Items[0].Ambiguous));
        await Organization("POST", "/platform/bansafe/incidents", """{"session":"support","occurredAt":"2026-09-22","note":"reported"}""", """{"data":{"incidentId":"i1","created":true,"sessionId":"s1","session":"support","occurredAt":"2026-09-22"}}""", async c => ResourceTests.True((await c.BanSafe.CreateIncidentAsync(new("support", "2026-09-22", "reported"), new() { IdempotencyKey = "fixture-key" })).Data.Data.Created));
        await Organization("POST", "/platform/bansafe/incidents/i1/retract", null, Envelope(Incident), async c => ResourceTests.Equal((await c.BanSafe.RetractIncidentAsync("i1")).Data.Data.ClosedBy, "owner"));
        await Organization("GET", "/platform/bansafe/claims?session=support&status=paid", null, Page(Claim), async c => ResourceTests.Equal((await c.BanSafe.ListClaimsAsync(new(Session: "support", Status: "paid"))).Items[0].AmountCents, 0.123456m));
        await Organization("GET", "/platform/bansafe/claims/c1", null, Envelope(Claim), async c => ResourceTests.Equal((await c.BanSafe.GetClaimAsync("c1")).Data.Data.Evidence.MeasuredHours, 1.5m));
        var options = new JsonSerializerOptions(); foreach (var json in new[] { "null", "0", "false", "\"unknown\"", "[]", "[1.5,2.25]" }) { var v = JsonSerializer.Deserialize<BanSafeSignalValue>(json, options); ResourceTests.Equal(JsonSerializer.Serialize(v, options), json); }
        foreach (var json in new[] { "{}", "[true]" }) { try { JsonSerializer.Deserialize<BanSafeSignalValue>(json, options); throw new Exception("Invalid signal value accepted"); } catch (JsonException) { } catch (InvalidOperationException) { } }
        Console.WriteLine("PASS 15 BanSafe routes, health authority/nulls, closed signal variants and six-decimal claims");
    }
    private static string Page(string json) => "{\"data\":[" + json + "],\"page\":{\"nextCursor\":null}}";
    private static string Envelope(string json) => "{\"data\":" + json + "}";
    private static Task Organization(string method, string path, string? body, string response, Func<OrganizationClient, Task> invoke) => BillingTests.Organization(method, path, body, response, invoke);
}
