using Polymorfa.Sdk;

internal static class BusinessTests
{
    private const string Product = """{"id":"item","name":"Item","price":"9007199254740993000","currency":"USD","hidden":false,"sanctioned":false,"media":{"images":[{"id":"photo","originalUrl":"https://example.com/image"}],"videos":[]},"status":{"canAppeal":true},"variant":{"availability":{"listings":[{"productId":"item","available":false,"options":[{"name":"size","value":"M"}]}]},"listingDetails":{"multiPrice":"1000"},"types":[],"properties":[]}}""";
    private const string Collection = """{"id":"collection","name":"Collection","products":[],"status":{"canAppeal":false,"rejectReason":"review"}}""";
    private const string Action = """{"success":true,"data":{"success":true}}""";
    private const string Accepted = """{"success":true,"data":{"requestId":"req_rpc"}}""";
    private const string Compliance = """{"entityName":"Merchant","entityType":"OTHER","isRegistered":false,"entityTypeCustom":"shop","customerCare":{"email":"care@example.com","landlineNumber":"","mobileNumber":""},"grievanceOfficer":{"name":"Support","email":"support@example.com","landlineNumber":"","mobileNumber":""}}""";
    public static async Task RunAsync()
    {
        await Messaging("GET", "/messaging/s/business/profile", null, """{"success":true,"data":{"id":"business","address":"Main Street","email":"care@example.com","description":"Shop","websites":[],"coverPhotoId":"photo","categories":[],"options":{},"hoursTimeZone":"UTC","hours":[]}}""", async c => ResourceTests.Equal((await c.Business.GetProfileAsync("s")).Data.Data.Address, "Main Street"));
        await Messaging("PATCH", "/messaging/s/business/profile", """{"description":"","websites":[],"hours":{"timeZone":"UTC","days":[{"dayOfWeek":"mon","mode":"specific_hours","openTime":0,"closeTime":60}]}}""", """{"success":true,"data":{"status":"OK"}}""", async c => ResourceTests.Equal(Value((await c.Business.UpdateProfileAsync("s", new(Description: "", Websites: [], Hours: new("UTC", [new("mon", "specific_hours", 0, 60)])))).Data.Data).Status, "OK"));
        await Messaging("PUT", "/messaging/s/business/profile/cover-photo", """{"base64":"AQID"}""", """{"success":true,"data":{"coverPhotoId":"photo"}}""", async c => ResourceTests.Equal(Value((await c.Business.SetCoverPhotoAsync("s", new(Base64: "AQID"))).Data.Data).CoverPhotoId, "photo"));
        await Messaging("DELETE", "/messaging/s/business/profile/cover-photo/photo", null, Accepted, async c => ResourceTests.Equal(((AcceptedCommand<BusinessProfileStatus>)(await c.Business.DeleteCoverPhotoAsync("s", "photo")).Data.Data).RequestId, "req_rpc"));
        await Messaging("GET", "/messaging/s/business/catalog?id=business&after=cursor&limit=5&width=10&height=20", null, Envelope("{\"next\":\"next\",\"products\":[" + Product + "]}"), async c => ResourceTests.Equal((await c.Business.GetCatalogAsync("s", new("business", "cursor", 5, 10, 20))).Data.Data.Products[0].Variant!.ListingDetails.MultiPrice, "1000"));
        await Messaging("POST", "/messaging/s/business/catalog", null, Action, async c => ResourceTests.True(Value((await c.Business.CreateCatalogAsync("s")).Data.Data).Success));
        await Messaging("PATCH", "/messaging/s/business/catalog/cart", """{"enabled":false}""", Action, async c => ResourceTests.True(Value((await c.Business.SetCartEnabledAsync("s", false)).Data.Data).Success));
        await Messaging("GET", "/messaging/s/business/products/item?id=business", null, Envelope(Product), async c => ResourceTests.Equal((await c.Business.GetProductAsync("s", "item", "business")).Data.Data.Price, "9007199254740993000"));
        await Messaging("POST", "/messaging/s/business/products", """{"name":"Item","images":[{"mediaUrl":"https://mmg.whatsapp.net/photo"}],"price":"1000","hidden":false}""", Envelope(Product), async c => ResourceTests.Equal(Value((await c.Business.CreateProductAsync("s", new("Item", [new(MediaUrl: "https://mmg.whatsapp.net/photo")], Price: "1000", Hidden: false))).Data.Data).Media.Images[0].Id, "photo"));
        await Messaging("PUT", "/messaging/s/business/products/item", """{"name":"Replacement","images":[]}""", Accepted, async c => ResourceTests.True((await c.Business.UpdateProductAsync("s", "item", new("Replacement", []))).Data.Data is AcceptedCommand<BusinessProduct>));
        await Messaging("DELETE", "/messaging/s/business/products/item", null, """{"success":true,"data":{"deletedCount":1}}""", async c => ResourceTests.Equal(Value((await c.Business.DeleteProductAsync("s", "item")).Data.Data).DeletedCount, 1));
        await Messaging("PATCH", "/messaging/s/business/products/item/visibility", """{"hidden":false}""", Action, async c => ResourceTests.True(Value((await c.Business.SetProductVisibilityAsync("s", "item", false)).Data.Data).Success));
        await Messaging("POST", "/messaging/s/business/products/item/appeal", """{"reason":"Reviewed"}""", Action, async c => ResourceTests.True(Value((await c.Business.AppealProductAsync("s", "item", new("Reviewed"))).Data.Data).Success));
        await Messaging("GET", "/messaging/s/business/collections?id=business&after=cursor&collectionLimit=2&itemLimit=4&width=10&height=20", null, Envelope("{\"next\":\"next\",\"collections\":[" + Collection + "]}"), async c => ResourceTests.Equal((await c.Business.ListCollectionsAsync("s", new("business", "cursor", 2, 4, 10, 20))).Data.Data.Collections[0].Status.RejectReason, "review"));
        await Messaging("GET", "/messaging/s/business/collections/collection?id=business&after=cursor&limit=5&width=10&height=20", null, Envelope(Collection), async c => ResourceTests.Equal((await c.Business.GetCollectionAsync("s", "collection", new("business", "cursor", 5, 10, 20))).Data.Data.Name, "Collection"));
        await Messaging("POST", "/messaging/s/business/collections", """{"name":"Collection","productIds":["item"]}""", """{"success":true,"data":{"id":"collection","reviewStatus":"pending"}}""", async c => ResourceTests.Equal(Value((await c.Business.CreateCollectionAsync("s", new("Collection", ["item"]))).Data.Data).ReviewStatus, "pending"));
        await Messaging("PATCH", "/messaging/s/business/collections/collection", """{"removeProductIds":[]}""", """{"success":true,"data":{"id":"collection","reviewStatus":"approved"}}""", async c => ResourceTests.Equal(Value((await c.Business.UpdateCollectionAsync("s", "collection", new(RemoveProductIds: []))).Data.Data).ReviewStatus, "approved"));
        await Messaging("DELETE", "/messaging/s/business/collections/collection", null, Action, async c => ResourceTests.True(Value((await c.Business.DeleteCollectionAsync("s", "collection")).Data.Data).Success));
        await Messaging("POST", "/messaging/s/business/collections/reorder", """{"moves":[{"collectionId":"collection","fromIndex":0,"toIndex":1}]}""", Action, async c => ResourceTests.True(Value((await c.Business.ReorderCollectionsAsync("s", new([new("collection", 0, 1)]))).Data.Data).Success));
        await Messaging("POST", "/messaging/s/business/collections/collection/appeal", """{"reason":"Reviewed"}""", Action, async c => ResourceTests.True(Value((await c.Business.AppealCollectionAsync("s", "collection", new("Reviewed"))).Data.Data).Success));
        await Messaging("POST", "/messaging/s/business/orders/order/lookup", """{"token":"fixture-token"}""", """{"success":true,"data":{"id":"order","createdAt":123,"price":{"subtotal":"1000","total":"1000","currency":"USD"},"products":[{"id":"item","price":"1000","currency":"USD","name":"Item","quantity":1.5,"variantProperties":"size=M"}]}}""", async c => ResourceTests.Equal(Value((await c.Business.GetOrderAsync("s", "order", new("fixture-token"))).Data.Data).Products[0].Quantity, 1.5m));
        await Messaging("GET", "/messaging/s/business/compliance", null, Envelope(Compliance), async c => ResourceTests.Equal((await c.Business.GetMerchantComplianceAsync("s")).Data.Data.GrievanceOfficer.Name, "Support"));
        await Messaging("PUT", "/messaging/s/business/compliance", Compliance, Accepted, async c => ResourceTests.True((await c.Business.SetMerchantComplianceAsync("s", new("Merchant", "OTHER", false, "shop", new("care@example.com", "", ""), new("Support", "support@example.com", "", "")))).Data.Data is AcceptedCommand<BusinessMerchantCompliance>));
        await Messaging("GET", "/messaging/s/business/linked-accounts", null, """{"success":true,"data":{"facebookPage":{"id":"page","displayName":"Page","hasActiveCTWAAd":true,"hasCreatedAd":false,"profilePictureUrl":"https://example.com","showOnProfile":true,"whatsAppAsPageButton":false}}}""", async c => ResourceTests.True((await c.Business.GetLinkedAccountsAsync("s")).Data.Data.FacebookPage!.HasActiveCtwaAd));
        await Messaging("GET", "/messaging/s/business/eligibility", null, """{"success":true,"data":{"features":[{"feature":"meta_verified","status":"eligible","showPrivacyInterstitialToNewUsers":false}]}}""", async c => ResourceTests.Equal((await c.Business.GetEligibilityAsync("s")).Data.Data.Features[0].ShowPrivacyInterstitialToNewUsers, false));
        using var client = new MessagingClient(Credential.OrganizationApiKey("pmfa_" + new string('a', 72)));
        try { await client.Business.SetCoverPhotoAsync("s", new()); throw new Exception("No image source accepted"); } catch (PolymorfaValidationException) { }
        try { await client.Business.CreateProductAsync("s", new("Bad", [new(Url: "https://example.com", Base64: "AQID")])); throw new Exception("Ambiguous image source accepted"); } catch (PolymorfaValidationException) { }
        Console.WriteLine("PASS 25 typed Business routes, asynchronous receipts, variant models and precise string prices");
    }
    private static T Value<T>(CommandResult<T> command) => command is CompletedCommand<T> completed ? completed.Value : throw new Exception("Expected completed command");
    private static string Envelope(string value) => "{\"success\":true,\"data\":" + value + "}";
    private static Task Messaging(string method, string path, string? body, string response, Func<MessagingClient, Task> invoke) => ResourceTests.Messaging(method, path, body, response, invoke);
}
