using Polymorfa.Sdk;

internal static class CampaignTests
{
    private const string Campaign = """{"id":"c1","name":"Customers","status":"future_state","templateId":null,"recipientListId":null,"recipientCount":2,"sentCount":1,"deliveredCount":1,"readCount":0,"failedCount":0,"skippedCount":1,"scheduledAt":null,"launchedAt":42,"completedAt":null,"createdAt":9007199254740993,"updatedAt":43,"sendWindow":{"timeZone":"UTC","days":["monday"],"hours":[{"start":"09:00","end":"24:00"}],"recipientTimeZone":false,"timeZoneVariable":"timeZone"},"variants":[{"key":"a","label":"A","weight":50,"blueprint":{"version":2,"source":"Hi {{name}}","future":false}}],"variantStrategy":{"winnerCriterion":"reply","holdoutPercent":10,"autoPromote":true,"testWindowMinutes":30},"experimentOutcome":{"winnerKey":"a","state":"promoted"},"messageVariations":null,"future":{"preserved":true}}""";
    private const string Analytics = """{"campaignId":"c1","recipientCount":2,"sentCount":1,"deliveredCount":1,"readCount":0,"failedCount":0,"skippedCount":1,"respondedCount":1,"responseRate":0.123456,"averageResponseTimeMs":null,"minResponseTimeMs":null,"maxResponseTimeMs":null,"experiment":{"criterion":"reply","outcome":{"reason":"insufficient_evidence","state":"inconclusive"},"holdoutCount":1,"reserveCount":1,"variants":[{"key":"a","label":"A","weight":50,"assigned":1,"sent":1,"delivered":1,"read":0,"replied":1,"outcomeRate":1}]}}""";
    private const string Recipient = """{"id":"r1","phone":"+15550001111","variables":{"active":false},"variantKey":null,"status":"sent","attempts":1,"lastError":null,"externalMessageId":"m1","queuedAt":42,"sentAt":43,"deliveredAt":null,"readAt":null,"failedAt":null,"respondedAt":null}""";
    private const string Added = """{"campaignId":"c1","added":1,"recipientCount":2,"duplicateCount":0,"invalidCount":1,"invalidRows":[{"row":2,"reason":"invalid_phone"}]}""";
    private static string Envelope(string body) => "{\"success\":true,\"data\":" + body + "}";
    private static string Operation => Envelope(Campaign[..^1] + ",\"operationId\":\"op1\"}");
    public static async Task RunAsync()
    {
        await Messaging("GET", "/messaging/projects/support/campaigns", null, Envelope("[" + Campaign + "]"), async c => ResourceTests.Equal((await c.Campaigns.ListAsync("support")).Data.Data[0].Status, "future_state"));
        await Messaging("POST", "/messaging/projects/support/campaigns", """{"name":"Customers","recipients":[{"phone":"+15550001111"}]}""", Envelope(Campaign), async c => ResourceTests.Equal((await c.Campaigns.CreateAsync("support", new("Customers", Recipients: [new("+15550001111")]))).Data.Data.CreatedAt, 9007199254740993L));
        await Messaging("GET", "/messaging/projects/support/campaigns/c1", null, Envelope(Campaign), async c => ResourceTests.Equal(((CampaignPromoted)(await c.Campaigns.RetrieveAsync("support", "c1")).Data.Data.ExperimentOutcome!).WinnerKey, "a"));
        await Messaging("PATCH", "/messaging/projects/support/campaigns/c1", """{"recipientListId":null,"scheduledAt":null,"variants":null,"variantStrategy":null,"sendWindow":null}""", Envelope(Campaign), async c => ResourceTests.Equal((await c.Campaigns.UpdateAsync("support", "c1", new() { RecipientListId = PatchValue<string>.Set(null), ScheduledAt = PatchValue<long?>.Set(null), Variants = PatchValue<IReadOnlyList<CampaignVariant>>.Set(null), VariantStrategy = PatchValue<CampaignVariantStrategy>.Set(null), SendWindow = PatchValue<CampaignSendWindowRequest>.Set(null) })).Data.Data.Name, "Customers"));
        await Messaging("GET", "/messaging/projects/support/campaigns/c1/analytics", null, Envelope(Analytics), async c => ResourceTests.Equal((await c.Campaigns.AnalyticsAsync("support", "c1")).Data.Data.ResponseRate, 0.123456m));
        await Messaging("POST", "/messaging/projects/support/campaigns/c1/launch", "{}", Operation, async c => ResourceTests.Equal((await c.Campaigns.LaunchAsync("support", "c1")).Data.Data.OperationId, "op1"));
        await Messaging("POST", "/messaging/projects/support/campaigns/c1/reschedule", """{"scheduledAt":null}""", Operation, async c => ResourceTests.Equal((await c.Campaigns.RescheduleAsync("support", "c1", new(null))).Data.Data.OperationId, "op1"));
        await Messaging("POST", "/messaging/projects/support/campaigns/c1/pause", null, Operation, async c => ResourceTests.Equal((await c.Campaigns.PauseAsync("support", "c1")).Data.Data.OperationId, "op1"));
        await Messaging("POST", "/messaging/projects/support/campaigns/c1/resume", null, Operation, async c => ResourceTests.Equal((await c.Campaigns.ResumeAsync("support", "c1")).Data.Data.OperationId, "op1"));
        await Messaging("POST", "/messaging/projects/support/campaigns/c1/stop", null, Envelope(Campaign[..^1] + ",\"operationId\":null}"), async c => ResourceTests.Equal((await c.Campaigns.StopAsync("support", "c1")).Data.Data.OperationId, null));
        await Messaging("GET", "/messaging/projects/support/campaigns/c1/recipients?status=sent&cursor=cursor1&limit=25", null, "{\"success\":true,\"data\":[" + Recipient + "],\"page\":{\"nextCursor\":null,\"hasMore\":false}}", async c => ResourceTests.Equal((await c.Campaigns.ListRecipientsAsync("support", "c1", new("sent", "cursor1", 25))).Data.Data[0].SentAt, 43L));
        await Messaging("POST", "/messaging/projects/support/campaigns/c1/recipients", """{"recipients":[{"phone":"+15550001111"}]}""", Envelope(Added), async c => ResourceTests.Equal((await c.Campaigns.AddRecipientsAsync("support", "c1", new([new("+15550001111")]))).Data.Data.InvalidRows[0].Row, 2));
        await Messaging("POST", "/messaging/projects/support/campaigns/c1/requeue", """{"includeSkippedError":false}""", Envelope("{\"requeued\":1}"), async c => ResourceTests.Equal((await c.Campaigns.RequeueAsync("support", "c1", new(false))).Data.Data.Requeued, 1L));
        await Organization("GET", "/platform/campaigns?projectId=p1&projectSlug=support", null, "{\"data\":[" + Campaign + "]}", async c => ResourceTests.True((await c.Campaigns.ListAsync(new("p1", "support"))).Data.Data[0].AdditionalFields!["future"].GetProperty("preserved").GetBoolean()));
        await Organization("POST", "/platform/campaigns", """{"projectId":"p1","name":"Customers","recipientCount":2}""", "{\"data\":" + Campaign + "}", async c => ResourceTests.Equal((await c.Campaigns.CreateAsync(new("p1", "Customers", RecipientCount: 2))).Data.Data.RecipientCount, 2L));
        await Organization("GET", "/platform/campaigns/c1?projectId=p1", null, """{"data":null}""", async c => ResourceTests.Equal((await c.Campaigns.RetrieveAsync("c1", new("p1"))).Data.Data, null));
        await Organization("PATCH", "/platform/campaigns/c1?projectId=p1", """{"recipientListId":null,"future":false}""", "{\"data\":" + Campaign + "}", async c => ResourceTests.Equal((await c.Campaigns.UpdateAsync("c1", new() { RecipientListId = PatchValue<string>.Set(null), AdditionalFields = new Dictionary<string, System.Text.Json.JsonElement> { ["future"] = System.Text.Json.JsonSerializer.SerializeToElement(false) } }, new("p1"))).Data.Data.Id, "c1"));
        await Organization("DELETE", "/platform/campaigns/c1?projectId=p1", null, """{"data":{"deleted":true}}""", async c => ResourceTests.True((await c.Campaigns.DeleteAsync("c1", new("p1"))).Data.Data["deleted"].GetBoolean()));
        await Organization("POST", "/platform/campaigns/c1/launch", null, """{"data":{"operationId":"op1"}}""", async c => ResourceTests.Equal((await c.Campaigns.LaunchAsync("c1")).Data.Data["operationId"].GetString(), "op1"));
        await Organization("POST", "/platform/campaigns/c1/pause", null, """{"data":{"accepted":true}}""", async c => ResourceTests.True((await c.Campaigns.PauseAsync("c1")).Data.Data["accepted"].GetBoolean()));
        await Organization("POST", "/platform/campaigns/c1/resume", null, """{"data":{"accepted":true}}""", async c => ResourceTests.True((await c.Campaigns.ResumeAsync("c1")).Data.Data["accepted"].GetBoolean()));
        await Organization("POST", "/platform/campaigns/c1/stop", null, """{"data":{"accepted":true}}""", async c => ResourceTests.True((await c.Campaigns.StopAsync("c1")).Data.Data["accepted"].GetBoolean()));
        await Organization("POST", "/platform/campaigns/c1/archive", null, """{"data":{"accepted":true}}""", async c => ResourceTests.True((await c.Campaigns.ArchiveAsync("c1")).Data.Data["accepted"].GetBoolean()));
        await Organization("POST", "/platform/campaigns/c1/duplicate", null, """{"data":{"campaignId":"c2"}}""", async c => ResourceTests.Equal((await c.Campaigns.DuplicateAsync("c1")).Data.Data["campaignId"].GetString(), "c2"));
        await Organization("POST", "/platform/campaigns/c1/requeue", null, """{"data":{"requeued":1}}""", async c => ResourceTests.Equal((await c.Campaigns.RequeueAsync("c1")).Data.Data["requeued"].GetInt32(), 1));
        await Organization("POST", "/platform/campaigns/c1/reschedule", """{"projectId":"p1","scheduledAt":null}""", """{"data":{"operationId":"op1"}}""", async c => ResourceTests.Equal((await c.Campaigns.RescheduleAsync("c1", new("p1", null))).Data.Data["operationId"].GetString(), "op1"));
        await Organization("GET", "/platform/campaigns/c1/analytics?projectId=p1", null, "{\"data\":" + Analytics + "}", async c => ResourceTests.True((await c.Campaigns.AnalyticsAsync("c1", new("p1"))).Data.Data.Experiment!.Outcome is CampaignInconclusive));
        await Organization("GET", "/platform/campaigns/c1/events?projectId=p1", null, """{"data":{"events":[]}}""", async c => ResourceTests.Equal((await c.Campaigns.EventsAsync("c1", new("p1"))).Data.Data["events"].GetArrayLength(), 0));
        await Organization("GET", "/platform/campaigns/c1/recipients?projectId=p1&status=sent&limit=25", null, "{\"data\":[" + Recipient + "],\"page\":{\"nextCursor\":null}}", async c => ResourceTests.Equal((await c.Campaigns.RecipientsAsync("c1", new("p1", "sent", Limit: 25))).Data.Data[0].VariantKey, null));
        await Organization("POST", "/platform/campaigns/c1/recipients", """{"projectId":"p1","recipients":[{"phone":"+15550001111"}]}""", "{\"data\":" + Added + "}", async c => ResourceTests.Equal((await c.Campaigns.AddRecipientsAsync("c1", new("p1", [new("+15550001111")]))).Data.Data.Added, 1L));
        await Organization("POST", "/platform/campaigns/c1/conversions", """{"projectId":"p1","recipientId":"r1","eventId":"order1","eventType":"purchase","occurredAt":"2026-09-22T00:00:00Z","value":{"amountMinor":1234,"currency":"USD"}}""", """{"data":{"id":"cv1","campaignId":"c1","recipientId":"r1","eventType":"purchase","occurredAt":"2026-09-22T00:00:00Z","value":{"amountMinor":1234,"currency":"USD"},"evidence":"customer_reported","attribution":{"outcome":"attributed","touchAt":"2026-09-21T00:00:00Z","windowDays":7},"recordedAt":"2026-09-22T00:00:00Z","replayed":true}}""", async c => ResourceTests.True((await c.Campaigns.RecordConversionAsync("c1", new("p1", "r1", "order1", "purchase", "2026-09-22T00:00:00Z", new(1234, "USD")))).Data.Data.Replayed));
        await Organization("GET", "/platform/campaigns/c1/conversions?projectId=p1", null, """{"data":{"campaignId":"c1","model":{"touch":"recipient_sent","windowDays":7,"correlation":"explicit_recipient"},"sentCount":2,"conversions":{"total":3,"attributed":2,"outsideWindow":1,"notSent":0,"optedOut":0},"convertedRecipients":1,"conversionRate":0.5,"values":[{"currency":"USD","evidence":"customer_reported","attributedConversions":2,"attributedAmountMinor":"90071992547409931234","unattributedConversions":1,"unattributedAmountMinor":"1234"}]}}""", async c => ResourceTests.Equal((await c.Campaigns.ConversionsAsync("c1", new("p1"))).Data.Data.Values[0].AttributedAmountMinor, "90071992547409931234"));
        using var client = new MessagingClient(Credential.OrganizationApiKey("pmfa_" + new string('a', 72))); try { await client.Campaigns.UpdateAsync("support", "c1", new()); throw new Exception("Empty edit accepted"); } catch (PolymorfaValidationException) { }
        Console.WriteLine("PASS both Campaign workflows, A/B outcomes, weighted blueprints, recipient cursors, nullable edits and reported currency values");
    }
    private static Task Messaging(string method, string path, string? body, string response, Func<MessagingClient, Task> invoke) => ResourceTests.Messaging(method, path, body, response, invoke);
    private static Task Organization(string method, string path, string? body, string response, Func<OrganizationClient, Task> invoke) => BillingTests.Organization(method, path, body, response, invoke);
}
