using System.Text.Json;
using Polymorfa.Sdk;

internal static class FlowTests
{
    private const string Id = "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee";
    private const string Draft = """{"id":"aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee","name":"Booking","status":"draft","version":"7.1","screenCount":1,"metaLinks":[],"createdAt":10,"updatedAt":20,"definition":{"version":"7.1","screens":[{"id":"START","terminal":true}]}}""";
    private const string Operation = """{"id":"op1","requestId":"provider1","flowId":"aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee","flowName":"Booking","sessionId":"s1","session":"support","action":"upload","state":"uncertain","resolution":null,"wabaId":null,"metaFlowId":null,"definitionDigest":"digest1","providerStatus":null,"errorCode":"provider_timeout","providerCode":null,"providerSubcode":null,"createdAt":10,"updatedAt":20,"completedAt":null}""";
    private const string ProviderResult = "{\"data\":{\"operation\":" + Operation + ",\"flow\":" + Draft + "}}";
    private const string Encryption = """{"custody":"managed","activeKeyId":null,"keys":[{"id":"key1","state":"uncertain","fingerprint":"sha1","publicKey":"PUBLIC KEY","errorCode":"provider_timeout","createdAt":10,"activatedAt":null,"retireAfter":null}]}""";
    private const string Endpoint = """{"id":"endpoint1","orgId":"o1","projectId":"p1","flowId":"aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee","sessionId":"s1","mode":"function","url":null,"functionId":"fn1","deploymentId":null,"enabled":false,"revision":2,"endpointUri":"https://api.polymorfa.com/flow/endpoint1","createdAt":10,"updatedAt":20}""";
    public static async Task RunAsync()
    {
        await Organization("GET", "/platform/flows?projectId=p1", null, "{\"data\":[" + Draft + "]}", async c => ResourceTests.Equal((await c.Project("p1").Flows.ListAsync()).Data[0].ScreenCount, 1));
        await Organization("POST", "/platform/flows", """{"name":"Booking","definition":{"version":"7.1"},"projectId":"p1"}""", Envelope(Draft), async c => ResourceTests.Equal((await c.Project("p1").Flows.CreateAsync(new("Booking", new Dictionary<string, JsonElement> { ["version"] = JsonSerializer.SerializeToElement("7.1") }))).Data.Definition["screens"].GetArrayLength(), 1));
        await Organization("GET", "/platform/flows/" + Id + "?projectId=p1", null, "{\"data\":null}", async c => ResourceTests.True((await c.Project("p1").Flows.RetrieveAsync(Id)).Data is null));
        await Organization("PATCH", "/platform/flows/" + Id, """{"expectedUpdatedAt":20,"name":"Booking","projectId":"p1"}""", Envelope(Draft), async c => ResourceTests.Equal((await c.Project("p1").Flows.UpdateAsync(Id, new(20, "Booking"))).Data.UpdatedAt, 20L));
        await Organization("DELETE", "/platform/flows/" + Id + "?projectId=p1", null, """{"data":{"ok":true}}""", async c => ResourceTests.True((await c.Project("p1").Flows.DeleteAsync(Id)).Data.Ok));
        await Organization("POST", "/platform/flows/" + Id + "/upload", """{"sessionId":"s1","categories":["APPOINTMENT_BOOKING"],"requestId":"provider1","projectId":"p1"}""", ProviderResult, async c => ResourceTests.Equal((await c.Project("p1").Flows.UploadAsync(Id, new("s1", ["APPOINTMENT_BOOKING"], "provider1"))).Data.Operation!.State, "uncertain"));
        await Organization("POST", "/platform/flows/" + Id + "/publish", """{"sessionId":"s1","projectId":"p1"}""", ProviderResult, async c => ResourceTests.Equal((await c.Project("p1").Flows.PublishAsync(Id, new("s1"))).Data.Operation!.ErrorCode, "provider_timeout"));
        await Organization("POST", "/platform/flows/" + Id + "/deprecate", """{"sessionId":"s1","projectId":"p1"}""", ProviderResult, async c => ResourceTests.Equal((await c.Project("p1").Flows.DeprecateAsync(Id, new("s1"))).Data.Flow.Name, "Booking"));
        await Organization("POST", "/platform/flows/" + Id + "/discard", """{"sessionId":"s1","projectId":"p1"}""", ProviderResult, async c => ResourceTests.True((await c.Project("p1").Flows.DiscardAsync(Id, new("s1"))).Data.Operation!.CompletedAt is null));
        await Organization("POST", "/platform/flows/" + Id + "/sync", """{"sessionId":"s1","projectId":"p1"}""", ProviderResult, async c => ResourceTests.Equal((await c.Project("p1").Flows.SyncAsync(Id, new("s1"))).Data.Operation!.RequestId, "provider1"));
        await Organization("GET", "/platform/flows/" + Id + "/receipts?projectId=p1", null, "{\"data\":[" + Operation + "]}", async c => ResourceTests.Equal((await c.Project("p1").Flows.ReceiptsAsync(Id)).Data[0].DefinitionDigest, "digest1"));
        await Organization("GET", "/platform/flows/" + Id + "/endpoint?sessionId=s1&projectId=p1", null, "{\"data\":{\"endpoint\":null,\"encryption\":" + Encryption + "}}", async c => ResourceTests.Equal((await c.Project("p1").Flows.EndpointAsync(Id, new("s1"))).Data.Encryption.Keys[0].State, "uncertain"));
        await Organization("PUT", "/platform/flows/" + Id + "/endpoint", """{"sessionId":"s1","functionId":"fn1","deploymentId":null,"enabled":false,"expectedRevision":2,"mode":"function","projectId":"p1"}""", "{\"data\":{\"endpoint\":" + Endpoint + ",\"encryption\":" + Encryption + "}}", async c => ResourceTests.True((await c.Project("p1").Flows.SetEndpointAsync(Id, new FunctionFlowEndpointRequest("s1", "fn1", PatchValue<string>.Set(null), false, 2))).Data.Endpoint.DeploymentId is null));
        await Organization("DELETE", "/platform/flows/" + Id + "/endpoint?sessionId=s1&projectId=p1", null, """{"data":{"ok":true}}""", async c => ResourceTests.True((await c.Project("p1").Flows.DeleteEndpointAsync(Id, new("s1"))).Data.Ok));
        await Organization("GET", "/platform/flows/" + Id + "/endpoint/receipts?sessionId=s1&limit=2&projectId=p1", null, """{"data":[{"id":"r1","flowId":"aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee","endpointId":"endpoint1","sessionId":"s1","mode":"function","action":"INIT","outcome":"succeeded","httpStatus":200,"errorCode":null,"keyId":"key1","functionInvocationId":"inv1","durationMs":12.5,"createdAt":10,"completedAt":20}]}""", async c => ResourceTests.Equal((await c.Project("p1").Flows.EndpointReceiptsAsync(Id, new("s1", 2))).Data[0].DurationMs, 12.5));
        await Organization("GET", "/platform/flow-encryption-keys?sessionId=s1&projectId=p1", null, Envelope(Encryption), async c => ResourceTests.True((await c.Project("p1").Flows.EncryptionKeyAsync(new("s1"))).Data.ActiveKeyId is null));
        await Organization("POST", "/platform/flow-encryption-keys/rotate", """{"sessionId":"s1","projectId":"p1"}""", Envelope(Encryption[..^1] + ",\"key\":{\"id\":\"key1\",\"state\":\"uncertain\",\"fingerprint\":\"sha1\",\"publicKey\":\"PUBLIC KEY\",\"errorCode\":\"provider_timeout\",\"createdAt\":10,\"activatedAt\":null,\"retireAfter\":null}}"), async c => ResourceTests.Equal((await c.Project("p1").Flows.RotateEncryptionKeyAsync(new("s1"))).Data.Key.Fingerprint, "sha1"));
        await Organization("PUT", "/platform/flows/" + Id + "/endpoint", """{"sessionId":"s1","url":"https://customer.example/flow","rotateSigningSecret":true,"mode":"forward","projectId":"p1"}""", "{\"data\":{\"endpoint\":" + Endpoint + ",\"signingSecret\":\"one-time-secret\",\"encryption\":" + Encryption + "}}", async c => { var result = (await c.Project("p1").Flows.SetEndpointAsync(Id, new ForwardFlowEndpointRequest("s1", "https://customer.example/flow", true))).Data; ResourceTests.Equal(result.SigningSecret, "one-time-secret"); ResourceTests.True(!result.ToString().Contains("one-time-secret")); });
        await Organization("PUT", "/platform/flows/" + Id + "/endpoint", """{"sessionId":"s1","url":"https://customer.example/direct","mode":"direct","projectId":"p1"}""", "{\"data\":{\"endpoint\":" + Endpoint + ",\"encryption\":" + Encryption + "}}", async c => ResourceTests.Equal((await c.Project("p1").Flows.SetEndpointAsync(Id, new DirectFlowEndpointRequest("s1", "https://customer.example/direct"))).Data.Endpoint.Id, "endpoint1"));
        using var client = new OrganizationClient(Credential.OrganizationApiKey("pmfa_" + new string('a', 72)));
        await Invalid(() => client.Project("p1").Flows.RetrieveAsync("bad")); await Invalid(() => client.Project("p1").Flows.EndpointReceiptsAsync(Id, new(Limit: 0))); await Invalid(() => client.Project("p1").Flows.SetEndpointAsync(Id, new DirectFlowEndpointRequest("s1", "https://user:pass@example.com"))); await Invalid(() => client.Project("p1").Flows.SetEndpointAsync(Id, new FunctionFlowEndpointRequest("s1", "")));
        using var fixture = new WireFixture(); var serve = fixture.ServeAsync("POST", "/platform/flows/" + Id + "/publish", """{"sessionId":"s1","projectId":"p1"}""", """{"error":{"code":"unavailable","message":"Try later"}}""", 503);
        using var retries = new OrganizationClient(Credential.OrganizationApiKey("pmfa_" + new string('a', 72)), new() { BaseUrl = fixture.Url, Timeout = TimeSpan.FromMilliseconds(300) });
        try { await retries.Project("p1").Flows.PublishAsync(Id, new("s1"), new() { IdempotencyKey = "key", MaxNetworkRetries = 3 }); throw new Exception("Retry accepted"); } catch (PolymorfaServerException e) { ResourceTests.Equal(e.Metadata!.Attempts, 1); }
        await serve;
        Console.WriteLine("PASS all 17 typed Flows operations, endpoint modes, immutable identity and one-attempt mutations");
    }
    private static string Envelope(string data) => "{\"data\":" + data + "}";
    private static Task Organization(string method, string path, string? body, string response, Func<OrganizationClient, Task> invoke) => BillingTests.Organization(method, path, body, response, invoke);
    private static async Task Invalid(Func<Task> action) { try { await action(); throw new Exception("Invalid Flow input accepted"); } catch (PolymorfaValidationException) { } }
}
