using Polymorfa.Sdk;

internal static class MessagingUtilityTests
{
    private const string Success = "{\"success\":true}";
    private const string Webhook = """{"id":"w1","tenantId":"o1","session":"support","url":"https://customer.example/hook","events":[],"retries":{"attempts":3,"delaySeconds":10,"policy":"fixed"},"headers":[{"name":"x-customer","value":"value"}],"enabled":false,"format":"native","createdAt":"2026-09-22"}""";
    private const string Chat = """{"conversation":{"id":"peer","bsuid":"US.123"},"kind":"direct","lastActivityAt":"2026-09-22","lastMessage":{"id":"m1","whatsapp_ids":{"official_api":"wa1"},"direction":"inbound","type":"image","timestamp":"2026-09-22"}}""";
    private const string Message = """{"id":"m1","whatsapp_ids":{"official_api":"wa1"},"direction":"inbound","type":"image","timestamp":"2026-09-22","conversation":{"id":"peer","sender":{"bsuid":"US.123"}},"fromMe":false,"caption":"Photo","media":[{"id":"media1","mimeType":"image/png","fileLength":123,"url":"/messaging/support/chats/peer/messages/m1/media"}],"mediaRetrieval":{"state":"stored"}}""";
    public static async Task RunAsync()
    {
        await Messaging("GET", "/messaging/webhooks", null, "{\"success\":true,\"data\":[" + Webhook + "]}", async c => ResourceTests.Equal((await c.Webhooks.ListAsync()).Data.Data[0].Headers[0].Name, "x-customer"));
        await Messaging("POST", "/messaging/webhooks", """{"url":"https://customer.example/hook","session":"support","events":[],"hmacKey":"fixture-signing-key","format":"native"}""", Envelope(Webhook), async c => ResourceTests.Equal((await c.Webhooks.CreateAsync(new("https://customer.example/hook", "support", [], "fixture-signing-key", Format: "native"))).Data.Data.Format, "native"));
        await Messaging("GET", "/messaging/webhooks/w1", null, Envelope(Webhook), async c => ResourceTests.True(!(await c.Webhooks.RetrieveAsync("w1")).Data.Data.Enabled));
        await Messaging("PUT", "/messaging/webhooks/w1", """{"events":[],"headers":[],"enabled":false}""", Envelope(Webhook), async c => ResourceTests.Equal((await c.Webhooks.UpdateAsync("w1", new(Events: [], Headers: [], Enabled: false))).Data.Data.Session, "support"));
        await Messaging("DELETE", "/messaging/webhooks/w1", null, Success, async c => ResourceTests.True((await c.Webhooks.DeleteAsync("w1")).Data.Success));
        await Messaging("POST", "/messaging/quicklinks", """{"projectId":"p1","customerId":"cu1","externalId":"client1","configuration":{"defaultMethod":null,"allowPhoneChange":false},"billingControls":{"limitCredits":null,"priority":2}}""", """{"success":true,"data":{"purpose":"initial","connectionGoal":"single","id":"q1","url":"https://customer.example/once","session":"support","expiresAt":null}}""", async c => { var q = (await c.QuickLinks.CreateAsync(new(ProjectId: "p1", CustomerId: "cu1", ExternalId: "client1", Configuration: new(DefaultMethod: PatchValue<string>.Set(null), AllowPhoneChange: false), BillingControls: new(null, 2)))).Data.Data; ResourceTests.Equal(q.Id, "q1"); ResourceTests.True(!q.ToString().Contains("/once")); });
        await Messaging("GET", "/messaging/quicklinks/q1", null, """{"success":true,"data":{"purpose":"initial","connectionGoal":"hybrid","hybridPhase":"ready","id":"q1","status":"connected","session":"support","expiresAt":null,"openedAt":null,"connectedAt":"2026-09-22","phone":null,"errorCode":null,"onboarding":{"stage":"connected","connection":"official_api","coexistence":true,"contactsSync":"pending","historySync":"partial","historyProgress":0.5,"sync":{"contacts":{"request":"accepted","receiptRecorded":true},"history":{"request":"accepted","receiptRecorded":true,"delivery":"partial"}},"errorCode":null}}}""", async c => ResourceTests.Equal((await c.QuickLinks.RetrieveAsync("q1")).Data.Data.Onboarding!.Sync.History.Delivery, "partial"));
        await Messaging("DELETE", "/messaging/quicklinks/q1", null, Success, async c => ResourceTests.True((await c.QuickLinks.CancelAsync("q1")).Data.Success));
        await Messaging("GET", "/messaging/quicklinks/availability?projectId=p1&session=support", null, """{"success":true,"data":{"allowed":false,"addConnection":"linked_devices","connections":[{"kind":"official_api","status":"connected","enabled":true}],"resumeQuickLinkId":"q1"}}""", async c => ResourceTests.Equal((await c.QuickLinks.AvailabilityAsync("p1", "support")).Data.Data.ResumeQuickLinkId, "q1"));
        await Messaging("GET", "/messaging/support/labels?includeObservation=true", null, """{"success":true,"data":{"policy":"follow","status":"observed","labels":[{"id":"l1","name":"Support","color":3,"orderIndex":1,"chatCount":2}],"observedAt":"2026-09-22"}}""", async c => ResourceTests.Equal((await c.Labels.ListAsync("support", new(true))).Data.Data.Observation!.Status, "observed"));
        await Messaging("POST", "/messaging/support/labels", """{"name":"Support","color":0}""", """{"success":true,"data":{"id":"l1","name":"Support","color":0}}""", async c => ResourceTests.Equal((await c.Labels.CreateAsync("support", new("Support", 0))).Data.Data.Color, 0));
        await Messaging("PUT", "/messaging/support/labels/l1", """{"name":"New","color":0}""", Success, async c => ResourceTests.True((await c.Labels.UpdateAsync("support", "l1", new("New", 0))).Data.Success));
        await Messaging("DELETE", "/messaging/support/labels/l1", null, Success, async c => ResourceTests.True((await c.Labels.DeleteAsync("support", "l1")).Data.Success));
        await Messaging("GET", "/messaging/support/labels/chats/peer", null, """{"success":true,"data":[{"id":"l1","name":"Support","color":3}]}""", async c => ResourceTests.Equal((await c.Labels.ListForChatAsync("support", "peer")).Data.Data.Labels[0].Id, "l1"));
        await Messaging("PUT", "/messaging/support/labels/chats/peer", """{"labels":[]}""", Success, async c => ResourceTests.True((await c.Labels.ReplaceForChatAsync("support", "peer", new([]))).Data.Success));
        await Messaging("POST", "/messaging/support/presence", """{"presence":"available"}""", """{"success":true,"data":{"status":"OK"}}""", async c => ResourceTests.Equal(((CompletedCommand<StatusResult>)(await c.Presence.SetAsync("support", new("available"))).Data.Data!).Value.Status, "OK"));
        await Messaging("GET", "/messaging/support/presence", null, """{"success":true,"data":{"authoritative":false,"desired":"available","desiredAt":"2026-09-22","lastSent":null,"lastSentAt":null}}""", async c => ResourceTests.True(!(await c.Presence.GetAsync("support")).Data.Data.Authoritative));
        await Messaging("GET", "/messaging/support/presence/peer", null, """{"success":true,"data":{"policy":"follow","status":"observed","stale":false,"typingPolicy":"follow","typingStatus":"observed","available":false,"chatState":{"sender":"peer","state":"paused","observedAt":"2026-09-22","stale":false}}}""", async c => ResourceTests.Equal((await c.Presence.GetForChatAsync("support", "peer")).Data.Data.ChatState!.State, "paused"));
        await Messaging("POST", "/messaging/support/presence/peer/subscribe", null, """{"success":true,"data":{"requestId":"op1","status":"queued"}}""", async c => ResourceTests.Equal(((AcceptedCommand<PresenceSubscription>)(await c.Presence.SubscribeAsync("support", "peer")).Data.Data).RequestId, "op1"));
        await Messaging("GET", "/messaging/support/chats?limit=2&kind=direct", null, "{\"success\":true,\"data\":[" + Chat + "],\"hasMore\":false,\"nextCursor\":null,\"previousCursor\":null}", async c => ResourceTests.Equal((await c.Chats.ListAsync("support", new(Limit: 2, Kind: "direct"))).Data.Data[0].LastMessage.WhatsAppIds.OfficialApi, "wa1"));
        await Messaging("GET", "/messaging/support/chats/peer", null, Envelope(Chat), async c => ResourceTests.Equal((await c.Chats.RetrieveAsync("support", "peer")).Data.Data.Conversation.Bsuid, "US.123"));
        await Messaging("GET", "/messaging/support/chats/peer/messages?limit=2&order=asc&direction=inbound&types=text%2Cimage", null, "{\"success\":true,\"data\":[" + Message + "],\"hasMore\":true,\"nextCursor\":\"older\",\"previousCursor\":null}", async c => ResourceTests.Equal((await c.Chats.ListMessagesAsync("support", "peer", new(Limit: 2, Order: "asc", Direction: "inbound", Types: "text,image"))).Data.NextCursor, "older"));
        await Messaging("GET", "/messaging/support/chats/peer/messages/m1", null, Envelope(Message), async c => { var m = (await c.Chats.RetrieveMessageAsync("support", "peer", "m1")).Data.Data; ResourceTests.Equal(m.MediaRetrieval!.State, "stored"); ResourceTests.Equal(m.Conversation.Sender!.Bsuid, "US.123"); });
        await Messaging("PUT", "/messaging/support/chats/peer/messages/m1", """{"text":"Updated","transport":"official_api"}""", Success, async c => ResourceTests.True((await c.Chats.EditMessageAsync("support", "peer", "m1", new("Updated", "official_api"))).Data.Success));
        await Messaging("DELETE", "/messaging/support/chats/peer/messages/m1?transport=official_api", null, Success, async c => ResourceTests.True((await c.Chats.DeleteMessageAsync("support", "peer", "m1", "official_api")).Data.Success));
        await Messaging("POST", "/messaging/support/chats/peer/archive", null, Success, async c => ResourceTests.True((await c.Chats.ArchiveAsync("support", "peer")).Data.Success));
        await Messaging("POST", "/messaging/support/chats/peer/unarchive", null, Success, async c => ResourceTests.True((await c.Chats.UnarchiveAsync("support", "peer")).Data.Success));
        await Messaging("PUT", "/messaging/support/chats/peer/disappearing", """{"durationSeconds":0}""", Success, async c => ResourceTests.True((await c.Chats.SetDisappearingTimerAsync("support", "peer", new(0))).Data.Success));
        using var token = new MessagingClient(Credential.ClientToken("pmfa_ct_fixture"));
        try { await token.Chats.ListAsync("support"); throw new Exception("Client read HMS"); } catch (PolymorfaConfigurationException) { }
        using var server = new MessagingClient(Credential.OrganizationApiKey("pmfa_" + new string('a', 72)));
        try { await server.QuickLinks.CreateAsync(new(Purpose: "add_connection")); throw new Exception("Link missing session"); } catch (PolymorfaValidationException) { }
        try { await server.QuickLinks.CreateAsync(new(Configuration: new(Testing: new()), BillingControls: new(null, 0))); throw new Exception("Testing billing accepted"); } catch (PolymorfaValidationException) { }
        Console.WriteLine("PASS Messaging webhook CRUD, QuickLink controls, observed labels/presence and hosted history CRUD");
    }
    private static string Envelope(string value) => "{\"success\":true,\"data\":" + value + "}";
    private static Task Messaging(string method, string path, string? body, string response, Func<MessagingClient, Task> invoke) => ResourceTests.Messaging(method, path, body, response, invoke);
}
