using Polymorfa.Sdk;

internal static class OfficialGroupTests
{
    private const string Accepted = "{\"success\":true,\"data\":{\"accepted\":true}}";
    public static async Task RunAsync()
    {
        await Messaging("GET", "/messaging/support/official-groups?limit=2&after=cursor", null, """{"success":true,"data":{"groups":[{"id":"g1","subject":"Support","createdAt":"2026-09-22"}],"cursors":{"after":"next"},"hasMore":true}}""", async c => ResourceTests.Equal((await c.OfficialGroups.ListAsync("support", new(2, After: "cursor"))).Data.Data.Cursors.After, "next"));
        await Messaging("POST", "/messaging/support/official-groups", """{"subject":"Support","description":"Customers","joinApprovalRequired":false}""", """{"success":true,"data":{"requestId":"op1"}}""", async c => ResourceTests.Equal((await c.OfficialGroups.CreateAsync("support", new("Support", "Customers", false))).Data.Data.RequestId, "op1"));
        await Messaging("GET", "/messaging/support/official-groups/g1", null, """{"success":true,"data":{"id":"g1","subject":"Support","description":"Customers","suspended":false,"createdAt":"2026-09-22","participantCount":1,"joinApprovalRequired":false,"participants":[{"bsuid":"US.123","id":"peer"}]}}""", async c => ResourceTests.Equal((await c.OfficialGroups.RetrieveAsync("support", "g1")).Data.Data.Participants[0].Bsuid, "US.123"));
        await Messaging("PATCH", "/messaging/support/official-groups/g1", """{"subject":"New","description":""}""", Accepted, async c => ResourceTests.True((await c.OfficialGroups.UpdateAsync("support", "g1", new("New", ""))).Data.Data.Accepted));
        await Messaging("DELETE", "/messaging/support/official-groups/g1", null, Accepted, async c => ResourceTests.True((await c.OfficialGroups.DeleteAsync("support", "g1")).Data.Data.Accepted));
        await Messaging("GET", "/messaging/support/official-groups/g1/invite-link", null, """{"success":true,"data":{"inviteLink":"https://customer.example/once"}}""", async c => ResourceTests.True(!(await c.OfficialGroups.GetInviteLinkAsync("support", "g1")).Data.Data.ToString().Contains("/once")));
        await Messaging("POST", "/messaging/support/official-groups/g1/invite-link/reset", null, """{"success":true,"data":{"inviteLink":"https://customer.example/new"}}""", async c => ResourceTests.Equal((await c.OfficialGroups.ResetInviteLinkAsync("support", "g1")).Data.Data.InviteLink, "https://customer.example/new"));
        await Messaging("POST", "/messaging/support/official-groups/g1/participants/remove", """{"participants":["peer"]}""", Accepted, async c => ResourceTests.True((await c.OfficialGroups.RemoveParticipantsAsync("support", "g1", ["peer"])).Data.Data.Accepted));
        await Messaging("GET", "/messaging/support/official-groups/g1/join-requests?after=cursor", null, """{"success":true,"data":{"items":[{"joinRequestId":"j1","user":{"id":"peer","bsuid":"US.123"},"createdAt":"2026-09-22"}],"cursors":{},"hasMore":false}}""", async c => ResourceTests.Equal((await c.OfficialGroups.ListJoinRequestsAsync("support", "g1", new(After: "cursor"))).Data.Data.Items[0].User.Bsuid, "US.123"));
        await Messaging("POST", "/messaging/support/official-groups/g1/join-requests/approve", """{"joinRequestIds":["j1","j2"]}""", """{"success":true,"data":{"succeeded":["j1"],"failed":[{"joinRequestId":"j2","errors":[{"code":403,"title":"Denied"}]}]}}""", async c => ResourceTests.Equal((await c.OfficialGroups.ApproveJoinRequestsAsync("support", "g1", ["j1", "j2"])).Data.Data.Failed[0].Errors[0].Code, 403L));
        await Messaging("POST", "/messaging/support/official-groups/g1/join-requests/reject", """{"joinRequestIds":["j1"]}""", """{"success":true,"data":{"succeeded":["j1"],"failed":[]}}""", async c => ResourceTests.Equal((await c.OfficialGroups.RejectJoinRequestsAsync("support", "g1", ["j1"])).Data.Data.Succeeded[0], "j1"));
        await Messaging("POST", "/messaging/support/official-groups/g1/pins", """{"operation":"pin","messageId":"m1","expirationDays":30}""", Accepted, async c => ResourceTests.True((await c.OfficialGroups.PinAsync("support", "g1", PinOfficialGroupMessageRequest.Pin("m1", 30))).Data.Data.Accepted));
        await Messaging("POST", "/messaging/support/official-groups/g1/pins", """{"operation":"unpin","messageId":"m1"}""", Accepted, async c => ResourceTests.True((await c.OfficialGroups.PinAsync("support", "g1", PinOfficialGroupMessageRequest.Unpin("m1"))).Data.Data.Accepted));
        using var token = new MessagingClient(Credential.ClientToken("pmfa_ct_fixture")); try { await token.OfficialGroups.ListAsync("support"); throw new Exception("Client used official groups"); } catch (PolymorfaConfigurationException) { }
        using var fixture = new WireFixture(); var serving = fixture.ServeAsync("POST", "/messaging/support/official-groups", """{"subject":"Support"}""", """{"error":{"code":"provider_unavailable","message":"Unavailable"}}""", 503); using var client = new MessagingClient(Credential.OrganizationApiKey("pmfa_" + new string('a', 72)), new() { BaseUrl = fixture.Url }); try { await client.OfficialGroups.CreateAsync("support", new("Support"), new() { IdempotencyKey = "fixture", MaxNetworkRetries = 3 }); throw new Exception("Expected rejection"); } catch (PolymorfaServerException e) { ResourceTests.Equal(e.Metadata!.Attempts, 1); }
        await serving;
        Console.WriteLine("PASS Official groups, asynchronous decisions, both pin operations, server guard and one-attempt provider writes");
    }
    private static Task Messaging(string method, string path, string? body, string response, Func<MessagingClient, Task> invoke) => ResourceTests.Messaging(method, path, body, response, invoke);
}
