using Polymorfa.Sdk;

internal static class OnboardingTests
{
    public static async Task RunAsync()
    {
        await Messaging("POST", "/messaging/cloud-api/embedded-signup", """{"quicklinkId":"q1","projectId":"p1","result":{"code":"fixture-code","wabaId":"waba1","phoneNumberId":"pn1","coexistence":false,"historySync":false}}""", """{"success":true,"data":{"stage":"connected"}}""", async c => ResourceTests.Equal((await c.CloudOnboarding.AdvanceAsync(new("q1", "p1", new("fixture-code", "waba1", "pn1", false, false)))).Data.Data.Stage, "connected"));
        await Messaging("POST", "/messaging/testing/p1/history-fixtures", """{"messages":[{"id":"m1","senderPhone":"+15550001111","text":"Hello","timestamp":9007199254740993,"fromMe":false}]}""", """{"fixtureId":"fixture1"}""", async c => ResourceTests.Equal((await c.Testing.CreateHistoryFixtureAsync("p1", new([new("m1", "+15550001111", "Hello", 9007199254740993L, false)]))).Data.FixtureId, "fixture1"));
        await Messaging("POST", "/messaging/testing/p1/events", """{"session":"support","event":"message.received","overrides":{"text":"Hello","video":false,"restrictionActive":false},"fromSession":"other"}""", """{"event":"message.received","session":"support","delivery":"simulated","eventId":null,"source":"runtime"}""", async c => ResourceTests.Equal((await c.Testing.TriggerEventAsync("p1", new("support", "message.received", new(Text: "Hello", Video: false, RestrictionActive: false), "other"))).Data.EventId, null));
        await Messaging("GET", "/messaging/testing/p1/events/fixtures", null, """{"fixtures":[{"name":"message.received","description":"Inbound","overrides":["text","from"]}]}""", async c => ResourceTests.Equal((await c.Testing.ListEventFixturesAsync("p1")).Data.Fixtures[0].Overrides[0], "text"));
        await Messaging("GET", "/messaging/testing/p1/numbers/support/phone", null, """{"session":"support","phone":"+15550001111","online":false,"devices":[{"deviceId":1}]}""", async c => ResourceTests.True(!(await c.Testing.GetPhoneAsync("p1", "support")).Data.Online));
        await Messaging("POST", "/messaging/testing/p1/numbers/support/phone/messages", """{"to":"+15550002222","text":"Hello"}""", """{"session":"support","to":"+15550002222","messageId":null}""", async c => ResourceTests.Equal((await c.Testing.SendPhoneMessageAsync("p1", "support", new("+15550002222", "Hello"))).Data.MessageId, null));
        await Messaging("POST", "/messaging/testing/p1/numbers/support/phone/devices/1/unlink", null, """{"session":"support","deviceId":1,"unlinked":true}""", async c => ResourceTests.True((await c.Testing.UnlinkPhoneDeviceAsync("p1", "support", 1)).Data.Unlinked));
        await Messaging("GET", "/messaging/projects/p1/observation-policy", null, """{"success":true,"data":{"projectId":"p1","presenceMode":"follow","typingMode":"off","labelMode":"off","quickReplyMode":"follow"}}""", async c => ResourceTests.Equal((await c.ObservationPolicies.RetrieveForProjectAsync("p1")).Data.Data.LabelMode, "off"));
        await Messaging("GET", "/messaging/support/observation-policy", null, """{"success":true,"data":{"sessionName":"support","projectId":"p1","project":{"presenceMode":"follow","typingMode":"off","labelMode":"off","quickReplyMode":"follow"},"override":{"presenceMode":"inherit","typingMode":"inherit","labelMode":"inherit","quickReplyMode":"off"},"effective":{"presenceMode":"follow","typingMode":"off","labelMode":"off","quickReplyMode":"off"}}}""", async c => ResourceTests.Equal((await c.ObservationPolicies.RetrieveForSessionAsync("support")).Data.Data.Effective.QuickReplyMode, "off"));
        await Messaging("GET", "/messaging/routing/hybrid?scope=project&projectId=p1", null, """{"success":true,"data":{"scope":"project","revision":"rev1","prefer":null,"allowedTransports":["official_api","linked_devices"]}}""", async c => ResourceTests.Equal((await c.HybridLink.GetPolicyAsync(HybridRoutingPolicyScope.Project("p1"))).Data.Data.Prefer, null));
        await Messaging("PUT", "/messaging/routing/hybrid?scope=session&projectId=p1&session=support", """{"expectedRevision":"rev1","prefer":null,"allowedTransports":[]}""", """{"success":true,"data":{"scope":"session","revision":"rev2","prefer":null,"allowedTransports":[]}}""", async c => ResourceTests.Equal((await c.HybridLink.SetPolicyAsync(HybridRoutingPolicyScope.Number("p1", "support"), new("rev1", null, []))).Data.Data.Revision, "rev2"));
        await Messaging("GET", "/messaging/support/hybrid-link", null, """{"success":true,"data":{"revision":"rev1","paused":false,"connections":[{"kind":"official_api","status":"connected","enabled":true}]}}""", async c => ResourceTests.True(!(await c.HybridLink.StateAsync("support")).Data.Data.Paused));
        await Messaging("PUT", "/messaging/support/hybrid-link", """{"expectedRevision":"rev1","paused":false}""", """{"success":true,"data":{"revision":"rev2","paused":false}}""", async c => ResourceTests.Equal((await c.HybridLink.SetPausedAsync("support", new("rev1", false))).Data.Data.Revision, "rev2"));
        using var token = new MessagingClient(Credential.ClientToken("pmfa_ct_fixture")); try { await token.Testing.GetPhoneAsync("p1", "support"); throw new Exception("Client operated phone"); } catch (PolymorfaConfigurationException) { }
        using var server = new MessagingClient(Credential.OrganizationApiKey("pmfa_" + new string('a', 72))); try { await server.Testing.UnlinkPhoneDeviceAsync("p1", "support", 0); throw new Exception("Primary device unlink accepted"); } catch (PolymorfaValidationException) { }
        ResourceTests.Equal(HybridLink.GraphTransportHeaders("official_api")["X-Polymorfa-Transport"], "official_api"); ResourceTests.True(!new EmbeddedSignupResult("fixture-code", "waba1", "pn1").ToString().Contains("fixture-code"));
        Console.WriteLine("PASS trusted onboarding, testing events/history/phone, resolved observation and Hybrid routing policies");
    }
    private static Task Messaging(string method, string path, string? body, string response, Func<MessagingClient, Task> invoke) => ResourceTests.Messaging(method, path, body, response, invoke);
}
