using Polymorfa.Sdk;
using static BillingTests;

internal static class SessionTests
{
    private const string Config = "{\"effective\":{\"observation\":{\"presenceMode\":\"off\",\"typingMode\":\"events\",\"labelMode\":\"cache\",\"quickReplyMode\":\"off\"},\"historySync\":{\"mode\":\"metadata_only\",\"requestFull\":false},\"hms\":{\"enabled\":false}},\"overrides\":{},\"sources\":{\"historySync.mode\":\"platform\",\"historySync.requestFull\":\"consent\",\"hms\":\"platform\",\"observation.presenceMode\":\"team\",\"observation.typingMode\":\"project\",\"observation.labelMode\":\"session\",\"observation.quickReplyMode\":\"platform\"},\"requestedHistory\":{\"mode\":\"deliver\",\"requestFull\":false},\"revisions\":{\"team\":1,\"project\":2,\"session\":3},\"historyConsent\":\"pending\",\"application\":{\"desiredGeneration\":4,\"appliedGeneration\":3,\"status\":\"pending\"}}";
    private const string Session = "{\"success\":true,\"data\":{\"sessionId\":\"s\",\"name\":\"Support\",\"tenantId\":\"team\",\"type\":\"linked_device\",\"testMode\":true,\"status\":\"connected\",\"configuration\":" + Config + ",\"newChatCapping\":null,\"createdAt\":\"2026-09-22\",\"updatedAt\":\"2026-09-22\"}}";
    private const string Tier = "{\"data\":{\"id\":\"quote\",\"status\":\"quoted\",\"failureReason\":null,\"expiresAtMs\":1000,\"quote\":{\"tier\":\"standard\",\"tierOverride\":null,\"amountCents\":0.123456,\"priceVersion\":\"v1\",\"action\":\"configure\",\"effectiveAtMs\":100,\"replacesWindowId\":null,\"hybridTransition\":{\"action\":\"keep\",\"survivingNumberId\":\"s\",\"keepTransport\":\"linked_devices\",\"status\":\"scheduled\",\"metaDisconnectRequired\":true}}}}";
    private const string Mode = "{\"presence\":\"dark\",\"typing\":\"off\",\"reads\":\"off\",\"pacing\":\"conversation\",\"onlineStart\":9,\"onlineEnd\":17}";
    private const string Safe = "{\"data\":{\"session\":\"s\",\"projectId\":\"p\",\"project\":" + Mode + ",\"override\":{\"presence\":\"inherit\",\"typing\":\"off\",\"reads\":\"inherit\",\"pacing\":\"inherit\"},\"effective\":" + Mode + ",\"applied\":{\"observedAt\":\"2026-09-22\",\"presence\":\"dark\",\"typing\":null,\"reads\":null,\"pacing\":\"conversation\"},\"mismatch\":false,\"entitled\":true,\"entitlementReason\":null}}";
    public static async Task RunAsync()
    {
        await Organization("GET", "/platform/sessions?projectId=p", null, "{\"data\":[{\"_id\":\"number\",\"_creationTime\":42,\"projectId\":\"p\",\"sessionId\":\"s\",\"name\":\"Support\",\"phone\":null,\"platform\":null,\"isBusiness\":false,\"testMode\":true,\"tierOverride\":null,\"status\":\"connected\",\"messageCount\":2,\"lastActiveAt\":null,\"paidUntil\":null}]}", async c => ResourceTests.Equal((await c.Sessions.ListAsync(new("p"))).Data.Data[0].CreationTime, 42L));
        await Organization("GET", "/platform/sessions/s", null, Session, async c => ResourceTests.Equal((await c.Sessions.RetrieveAsync("s")).Data.Data.Configuration!.Sources.HistorySyncRequestFull, "consent"));
        await Organization("PUT", "/platform/sessions/s", "{\"configuration\":{\"set\":{\"historySync\":{\"mode\":\"deliver\"}},\"reset\":[\"observation.typingMode\"]},\"revision\":3}", Session, async c => ResourceTests.Equal((await c.Sessions.UpdateAsync("s", new(new(new(HistorySync: new(Mode: "deliver")), ["observation.typingMode"]), 3))).Data.Data.Configuration!.Application!.Status, "pending"));
        await Organization("POST", "/platform/sessions/s/start", "{\"projectId\":\"p\"}", "{\"data\":{\"starting\":true,\"sessionId\":\"s\"}}", async c => ResourceTests.True((await c.Sessions.StartAsync("s", new("p"))).Data.Data.Starting));
        await Organization("POST", "/platform/sessions/s/stop", "{}", "{\"data\":{\"stopping\":true,\"sessionId\":\"s\"}}", async c => ResourceTests.True((await c.Sessions.StopAsync("s")).Data.Data.Stopping));
        await Organization("POST", "/platform/sessions/stop", "{\"sessionIds\":[\"s\"],\"projectId\":\"p\"}", "{\"data\":{\"stopping\":1}}", async c => ResourceTests.Equal((await c.Sessions.StopManyAsync(new(["s"], "p"))).Data.Data.Stopping, 1));
        await Organization("DELETE", "/platform/sessions/s", null, "{\"data\":{\"removed\":true,\"sessionId\":\"s\"}}", async c => ResourceTests.True((await c.Sessions.DeleteAsync("s")).Data.Data.Removed));
        await Organization("POST", "/platform/sessions/delete", "{\"sessionIds\":[\"s\"]}", "{\"data\":{\"removed\":1}}", async c => ResourceTests.Equal((await c.Sessions.DeleteManyAsync(new(["s"]))).Data.Data.Removed, 1));
        await Organization("POST", "/platform/sessions/s/tier-quotes", "{\"tierOverride\":null,\"hybridResolution\":{\"action\":\"keep\",\"transport\":\"linked_devices\"}}", Tier, async c => ResourceTests.Equal((await c.Sessions.QuoteTierChangeAsync("s", new(null, HybridResolution: new("keep", Transport: "linked_devices")))).Data.Data.Quote.AmountCents, 0.123456m));
        await Organization("GET", "/platform/sessions/s/tier-quotes/quote", null, Tier, async c => ResourceTests.True((await c.Sessions.RetrieveTierChangeAsync("s", "quote")).Data.Data.Quote.HybridTransition!.MetaDisconnectRequired!.Value));
        await Organization("PATCH", "/platform/sessions/s", "{\"quoteId\":\"quote\"}", Tier, async c => ResourceTests.Equal((await c.Sessions.SetTierOverrideAsync("s", new("quote"))).Data.Data.Status, "quoted"));
        await Organization("GET", "/platform/sessions/s/capabilities", null, "{\"data\":{\"session\":\"s\",\"projectId\":\"p\",\"status\":\"synced\",\"syncedAt\":\"2026-09-22\",\"checkedAt\":null,\"accountType\":\"personal\",\"capabilities\":[{\"key\":\"channels\",\"source\":\"server\",\"kind\":\"feature\",\"unit\":null,\"value\":true},{\"key\":\"messageEdit.windowSeconds\",\"source\":\"client_default\",\"kind\":\"limit\",\"unit\":\"seconds\",\"value\":900},{\"key\":\"polls.endTime\",\"source\":null,\"kind\":\"feature\",\"unit\":null,\"value\":null}]}}", async c => { var values = (await c.Sessions.GetCapabilitiesAsync("s")).Data.Data.Capabilities; ResourceTests.Equal(((LimitCapability)values[1]).Value, 900L); ResourceTests.Equal(((FeatureCapability)values[2]).Value, null); });
        await Organization("GET", "/platform/sessions/s/safe-mode", null, Safe, async c => ResourceTests.Equal((await c.Sessions.GetSafeModeAsync("s")).Data.Data.Override.Presence, "inherit"));
        await Organization("PUT", "/platform/sessions/s/safe-mode", "{\"typing\":\"inherit\"}", Safe, async c => ResourceTests.Equal((await c.Sessions.UpdateSafeModeAsync("s", new(Typing: "inherit"))).Data.Data.Effective.Pacing, "conversation"));
        await Organization("GET", "/platform/session-configuration", null, "{\"data\":" + Config + "}", async c => ResourceTests.Equal((await c.Configuration.RetrieveAsync()).Data.Revisions.Team, 1L));
        await Organization("PUT", "/platform/session-configuration", "{\"configuration\":{\"reset\":[\"hms\"]},\"revision\":1}", "{\"data\":" + Config + "}", async c => ResourceTests.Equal((await c.Configuration.UpdateAsync(new(new(Reset: ["hms"]), 1))).Data.Effective.Hms.Enabled, false));
        await Organization("GET", "/platform/session-configuration?projectId=p", null, "{\"data\":" + Config + "}", async c => ResourceTests.Equal((await c.Project("p").Configuration.RetrieveAsync()).Data.Sources.TypingMode, "project"));
        await Organization("PUT", "/platform/session-configuration", "{\"configuration\":{\"set\":{\"observation\":{\"presenceMode\":\"cache\"}}},\"revision\":2,\"projectId\":\"p\"}", "{\"data\":" + Config + "}", async c => ResourceTests.Equal((await c.Project("p").Configuration.UpdateAsync(new(new(new(Observation: new(PresenceMode: "cache"))), 2))).Data.Revisions.Project, 2L));
        Console.WriteLine("PASS 14 typed number APIs and four configuration inheritance requests");
    }
}
