namespace Polymorfa.Sdk;

public sealed class Business : Resource
{
    internal Business(HttpTransport http) : base(http) { }
    private static string Path(string session) => $"/messaging/{E(session)}/business";
    private static string Profile(string session) => Path(session) + "/profile";
    private static string Product(string session, string product) => Path(session) + "/products/" + E(product);
    private static string Collection(string session, string collection) => Path(session) + "/collections/" + E(collection);
    public Task<ApiResponse<SuccessEnvelope<BusinessProfile>>> GetProfileAsync(string session, RequestOptions? options = null) => Get<SuccessEnvelope<BusinessProfile>>(Profile(session), options);
    public Task<ApiResponse<SuccessEnvelope<CommandResult<BusinessProfileStatus>>>> UpdateProfileAsync(string session, BusinessProfileUpdateRequest body, RequestOptions? options = null) => Patch<SuccessEnvelope<CommandResult<BusinessProfileStatus>>>(Profile(session), body, options);
    public Task<ApiResponse<SuccessEnvelope<CommandResult<BusinessCoverPhotoResult>>>> SetCoverPhotoAsync(string session, PictureRequest body, RequestOptions? options = null) { ValidateImage(body.Url, body.Base64); return Put<SuccessEnvelope<CommandResult<BusinessCoverPhotoResult>>>(Profile(session) + "/cover-photo", body, options); }
    public Task<ApiResponse<SuccessEnvelope<CommandResult<BusinessProfileStatus>>>> DeleteCoverPhotoAsync(string session, string coverPhotoId, RequestOptions? options = null) => Delete<SuccessEnvelope<CommandResult<BusinessProfileStatus>>>(Profile(session) + "/cover-photo/" + E(coverPhotoId), options);
    public Task<ApiResponse<SuccessEnvelope<BusinessCatalogPage>>> GetCatalogAsync(string session, BusinessCatalogParameters parameters, RequestOptions? options = null) => Get<SuccessEnvelope<BusinessCatalogPage>>(Path(session) + "/catalog", options, parameters);
    public Task<ApiResponse<SuccessEnvelope<CommandResult<BusinessActionSuccess>>>> CreateCatalogAsync(string session, RequestOptions? options = null) => Post<SuccessEnvelope<CommandResult<BusinessActionSuccess>>>(Path(session) + "/catalog", null, options);
    public Task<ApiResponse<SuccessEnvelope<CommandResult<BusinessActionSuccess>>>> SetCartEnabledAsync(string session, bool enabled, RequestOptions? options = null) => Patch<SuccessEnvelope<CommandResult<BusinessActionSuccess>>>(Path(session) + "/catalog/cart", new { enabled }, options);
    public Task<ApiResponse<SuccessEnvelope<BusinessProduct>>> GetProductAsync(string session, string productId, string businessId, RequestOptions? options = null) => Get<SuccessEnvelope<BusinessProduct>>(Product(session, productId), options, new { id = businessId });
    public Task<ApiResponse<SuccessEnvelope<CommandResult<BusinessProduct>>>> CreateProductAsync(string session, BusinessProductMutationRequest body, RequestOptions? options = null) { ValidateProduct(body); return Post<SuccessEnvelope<CommandResult<BusinessProduct>>>(Path(session) + "/products", body, options); }
    public Task<ApiResponse<SuccessEnvelope<CommandResult<BusinessProduct>>>> UpdateProductAsync(string session, string productId, BusinessProductMutationRequest body, RequestOptions? options = null) { ValidateProduct(body); return Put<SuccessEnvelope<CommandResult<BusinessProduct>>>(Product(session, productId), body, options); }
    public Task<ApiResponse<SuccessEnvelope<CommandResult<BusinessProductDeleteResult>>>> DeleteProductAsync(string session, string productId, RequestOptions? options = null) => Delete<SuccessEnvelope<CommandResult<BusinessProductDeleteResult>>>(Product(session, productId), options);
    public Task<ApiResponse<SuccessEnvelope<CommandResult<BusinessActionSuccess>>>> SetProductVisibilityAsync(string session, string productId, bool hidden, RequestOptions? options = null) => Patch<SuccessEnvelope<CommandResult<BusinessActionSuccess>>>(Product(session, productId) + "/visibility", new { hidden }, options);
    public Task<ApiResponse<SuccessEnvelope<CommandResult<BusinessActionSuccess>>>> AppealProductAsync(string session, string productId, BusinessCatalogAppealRequest body, RequestOptions? options = null) => Post<SuccessEnvelope<CommandResult<BusinessActionSuccess>>>(Product(session, productId) + "/appeal", body, options);
    public Task<ApiResponse<SuccessEnvelope<BusinessCollectionPage>>> ListCollectionsAsync(string session, BusinessCollectionsParameters parameters, RequestOptions? options = null) => Get<SuccessEnvelope<BusinessCollectionPage>>(Path(session) + "/collections", options, parameters);
    public Task<ApiResponse<SuccessEnvelope<BusinessCollection>>> GetCollectionAsync(string session, string collectionId, BusinessCatalogParameters parameters, RequestOptions? options = null) => Get<SuccessEnvelope<BusinessCollection>>(Collection(session, collectionId), options, parameters);
    public Task<ApiResponse<SuccessEnvelope<CommandResult<BusinessCollectionMutationResult>>>> CreateCollectionAsync(string session, BusinessCollectionCreateRequest body, RequestOptions? options = null) => Post<SuccessEnvelope<CommandResult<BusinessCollectionMutationResult>>>(Path(session) + "/collections", body, options);
    public Task<ApiResponse<SuccessEnvelope<CommandResult<BusinessCollectionMutationResult>>>> UpdateCollectionAsync(string session, string collectionId, BusinessCollectionUpdateRequest body, RequestOptions? options = null) => Patch<SuccessEnvelope<CommandResult<BusinessCollectionMutationResult>>>(Collection(session, collectionId), body, options);
    public Task<ApiResponse<SuccessEnvelope<CommandResult<BusinessActionSuccess>>>> DeleteCollectionAsync(string session, string collectionId, RequestOptions? options = null) => Delete<SuccessEnvelope<CommandResult<BusinessActionSuccess>>>(Collection(session, collectionId), options);
    public Task<ApiResponse<SuccessEnvelope<CommandResult<BusinessActionSuccess>>>> ReorderCollectionsAsync(string session, BusinessCollectionReorderRequest body, RequestOptions? options = null) => Post<SuccessEnvelope<CommandResult<BusinessActionSuccess>>>(Path(session) + "/collections/reorder", body, options);
    public Task<ApiResponse<SuccessEnvelope<CommandResult<BusinessActionSuccess>>>> AppealCollectionAsync(string session, string collectionId, BusinessCatalogAppealRequest body, RequestOptions? options = null) => Post<SuccessEnvelope<CommandResult<BusinessActionSuccess>>>(Collection(session, collectionId) + "/appeal", body, options);
    public Task<ApiResponse<SuccessEnvelope<CommandResult<BusinessOrder>>>> GetOrderAsync(string session, string orderId, BusinessOrderLookupRequest body, RequestOptions? options = null) => Post<SuccessEnvelope<CommandResult<BusinessOrder>>>(Path(session) + "/orders/" + E(orderId) + "/lookup", body, options);
    public Task<ApiResponse<SuccessEnvelope<BusinessMerchantCompliance>>> GetMerchantComplianceAsync(string session, RequestOptions? options = null) => Get<SuccessEnvelope<BusinessMerchantCompliance>>(Path(session) + "/compliance", options);
    public Task<ApiResponse<SuccessEnvelope<CommandResult<BusinessMerchantCompliance>>>> SetMerchantComplianceAsync(string session, BusinessMerchantCompliance body, RequestOptions? options = null) => Put<SuccessEnvelope<CommandResult<BusinessMerchantCompliance>>>(Path(session) + "/compliance", body, options);
    public Task<ApiResponse<SuccessEnvelope<BusinessLinkedAccounts>>> GetLinkedAccountsAsync(string session, RequestOptions? options = null) => Get<SuccessEnvelope<BusinessLinkedAccounts>>(Path(session) + "/linked-accounts", options);
    public Task<ApiResponse<SuccessEnvelope<BusinessEligibility>>> GetEligibilityAsync(string session, RequestOptions? options = null) => Get<SuccessEnvelope<BusinessEligibility>>(Path(session) + "/eligibility", options);
    private static void ValidateProduct(BusinessProductMutationRequest body)
    {
        foreach (var image in body.Images) if (new[] { image.Url, image.Base64, image.MediaUrl }.Count(v => v is not null) != 1) throw new PolymorfaValidationException("Product images require exactly one source.", "invalid_parameter");
    }
    private static void ValidateImage(string? url, string? base64) { if ((url is null) == (base64 is null)) throw new PolymorfaValidationException("Cover photo requires exactly one source.", "invalid_parameter"); }
}
