using System.Text.Json;

namespace Polymorfa.Sdk;

public static partial class Webhooks
{
    private static WebhookEvent Typed<T>(WebhookEnvelope envelope) => new TypedWebhookEvent<T>(envelope, envelope.Payload.Deserialize<T>(HttpTransport.Json) ?? throw new PolymorfaValidationException("Invalid webhook payload.", "invalid_webhook_event"));
    private static string? Field(WebhookEnvelope envelope, string key) => envelope.Payload.ValueKind == JsonValueKind.Object && envelope.Payload.TryGetProperty(key, out var value) && value.ValueKind == JsonValueKind.String ? value.GetString() : null;
    private static WebhookEvent ParsePayload(WebhookEnvelope envelope) => envelope.Event switch
    {
        "bansafe.action" => Typed<BanSafeActionPayload>(envelope),
        "bansafe.claim" => Typed<BanSafeClaimPayload>(envelope),
        "bansafe.health_threshold" => Typed<BanSafeHealthThresholdPayload>(envelope),
        "bansafe.incident" => Typed<BanSafeIncidentPayload>(envelope),
        "blocklist.update" => Typed<BlocklistUpdatePayload>(envelope),
        "business.quick_reply.update" => Typed<BusinessQuickReplyUpdatePayload>(envelope),
        "call.accepted" => Typed<CallAcceptedPayload>(envelope),
        "call.connection_joined" => Typed<CallConnectionJoinedPayload>(envelope),
        "call.connection_left" => Typed<CallConnectionLeftPayload>(envelope),
        "call.ended" => Typed<CallEndedPayload>(envelope),
        "call.missed" => Typed<CallMissedPayload>(envelope),
        "call.participant_joined" or "call.participant_state" => Typed<CallParticipantPayload>(envelope),
        "call.participant_left" => Typed<CallParticipantLeftPayload>(envelope),
        "call.permission_changed" => Typed<CallPermissionChangedPayload>(envelope),
        "call.received" => Typed<CallReceivedPayload>(envelope),
        "call.rejected" => Typed<CallRejectedPayload>(envelope),
        "call.telemetry" => Typed<CallTelemetryPayload>(envelope),
        "campaign.cap_reached" => Typed<CampaignCapReachedPayload>(envelope),
        "campaign.cold_blocked" => Typed<CampaignColdBlockedPayload>(envelope),
        "campaign.completed" => Typed<CampaignCompletedPayload>(envelope),
        "campaign.failed" => Typed<CampaignFailedPayload>(envelope),
        "campaign.launched" => Typed<CampaignLaunchedPayload>(envelope),
        "campaign.paused" => Typed<CampaignPausedPayload>(envelope),
        "campaign.recipient_failed" => Typed<CampaignRecipientFailedPayload>(envelope),
        "campaign.recipient_sent" => Typed<CampaignRecipientSentPayload>(envelope),
        "campaign.recipient_skipped" => Typed<CampaignRecipientSkippedPayload>(envelope),
        "campaign.rescheduled" => Typed<CampaignRescheduledPayload>(envelope),
        "campaign.resumed" => Typed<CampaignResumedPayload>(envelope),
        "campaign.stopped" => Typed<CampaignStoppedPayload>(envelope),
        "campaign.throttled" => Typed<CampaignThrottledPayload>(envelope),
        "chat.archive" => Typed<ChatArchivePayload>(envelope),
        "chat.clear" => Typed<ChatClearPayload>(envelope),
        "chat.delete" => Typed<ChatDeletePayload>(envelope),
        "chat.mute" => Typed<ChatMutePayload>(envelope),
        "chat.read" => Typed<ChatReadPayload>(envelope),
        "command.result" => Typed<CommandResultPayload>(envelope),
        "contact.opted_in" or "contact.opted_out" => Typed<ContactOptPayload>(envelope),
        "contact.sync" => Typed<ContactsSyncPayload>(envelope),
        "contact.update" => Typed<ContactUpdatePayload>(envelope),
        "customer.created" or "customer.archived" or "customer.restored" => Typed<CustomerEventPayload>(envelope),
        "customer.updated" => Typed<CustomerUpdatedPayload>(envelope),
        "customer.enabled" => Typed<CustomerEnabledPayload>(envelope),
        "customer.archiving" => Typed<CustomerArchivingPayload>(envelope),
        "customer.pairing_link.created" or "customer.pairing_link.opened" or "customer.pairing_link.expired" => Typed<CustomerPairingLinkPayload>(envelope),
        "customer.pairing_link.connected" => Typed<CustomerPairingLinkConnectedPayload>(envelope),
        "customer.pairing_link.failed" => Typed<CustomerPairingLinkFailedPayload>(envelope),
        "customer.pairing_link.revoked" => Typed<CustomerPairingLinkRevokedPayload>(envelope),
        "customer.number.attached" => Typed<CustomerNumberAttachedPayload>(envelope),
        "customer.number.transferred" => Typed<CustomerNumberTransferredPayload>(envelope),
        "customer.number.disconnected" => Typed<CustomerNumberDisconnectedPayload>(envelope),
        "group.participant" => Typed<GroupParticipantPayload>(envelope),
        "group.update" => Typed<GroupUpdatePayload>(envelope),
        "history.sync" => Field(envelope, "kind") == "history" ? Typed<CloudHistorySyncPayload>(envelope) : Typed<LinkedHistorySyncPayload>(envelope),
        "labels.update" => Typed<LabelsUpdatePayload>(envelope),
        "message.ack" => Typed<MessageAckPayload>(envelope),
        "message.delete" => Typed<MessageDeletePayload>(envelope),
        "message.echo" => Typed<MessageEchoPayload>(envelope),
        "message.edited" or "message.revoked" or "message.update" => Typed<LinkedDeviceMessagePayload>(envelope),
        "message.failed" => Typed<MessageFailedPayload>(envelope),
        "message.reaction" or "message.received" => Field(envelope, "timestamp") is not null ? Typed<CloudMessagePayload>(envelope) : Typed<LinkedDeviceMessagePayload>(envelope),
        "message.sent" => Typed<MessageSentPayload>(envelope),
        "message.vote" => Typed<PollVotePayload>(envelope),
        "newsletter.update" => Typed<NewsletterUpdatePayload>(envelope),
        "order.payment_updated" => Field(envelope, "kind") switch
        {
            "payment_status" => Typed<PaymentStatusUpdatedPayload>(envelope),
            "payment_method_selected" => Typed<PaymentMethodSelectedPayload>(envelope),
            _ => new UnknownWebhookEvent(envelope)
        },
        "presence.update" => Typed<PresenceUpdatePayload>(envelope),
        "session.capabilities_updated" => Typed<SessionCapabilitiesUpdatedPayload>(envelope),
        "session.connected" => Typed<SessionConnectedPayload>(envelope),
        "session.logged_out" => Typed<SessionLoggedOutPayload>(envelope),
        "session.phone_offline" => Typed<SessionPhoneOfflinePayload>(envelope),
        "session.restriction_updated" => Typed<SessionRestrictionUpdatedPayload>(envelope),
        "session.status" => Field(envelope, "source") == "meta" ? Typed<CloudAccountStatusPayload>(envelope) : Typed<RuntimeSessionStatusPayload>(envelope),
        "template.status" => Field(envelope, "kind") is not null ? Typed<CloudTemplateStatusPayload>(envelope) : Typed<RuntimeTemplateStatusPayload>(envelope),
        "usage.recorded" => Typed<UsageRecordedPayload>(envelope),
        "voice.asset_failed" => Typed<VoiceAssetFailedPayload>(envelope),
        "voice.asset_ready" => Typed<VoiceAssetReadyPayload>(envelope),
        _ => new UnknownWebhookEvent(envelope)
    };
}
