<?php

declare(strict_types=1);

namespace Polymorfa;

/**
 * @phpstan-type CallOutcome array{total:int,answered:int,missed:int,declined:int,failed:int,ringing:int,answerRate:int|float|null,talkSeconds:int|float,timedAnswered:int,timedPickup:int,averageTalkSeconds:int|float|null,medianTalkSeconds:int|float|null,p95TalkSeconds:int|float|null,averagePickupMs:int|float|null,p95PickupMs:int|float|null,shortAnswered:int,video:int}
 * @phpstan-type MediaQuality array{measuredCalls:int,averageJitterMs:int|float|null,averageRttMs:int|float|null,packetsLost:?int}
 * @phpstan-type AppQuality array{measuredCalls:int,averageJitterMs:int|float|null,averageRttMs:int|float|null,packetLossRate:int|float|null,reconnects:?int}
 * @phpstan-type CodeCount array{code:string,count:int}
 * @phpstan-type FollowUp array{eligibleMissed:int,returnedWithin24h:int,rate:int|float|null,averageDelayMs:int|float|null,pendingWindow:int,unknownContact:int}
 * @phpstan-type Calls array{total:int,answered:int,missed:int,declined:int,failed:int,ringing:int,answerRate:int|float|null,talkSeconds:int|float,timedAnswered:int,timedPickup:int,averageTalkSeconds:int|float|null,medianTalkSeconds:int|float|null,p95TalkSeconds:int|float|null,averagePickupMs:int|float|null,p95PickupMs:int|float|null,shortAnswered:int,video:int,directions:array{inbound:CallOutcome,outbound:CallOutcome},mediaQuality:MediaQuality,appQuality:AppQuality,endReasons:list<CodeCount>,appErrors:list<CodeCount>,transports:list<CodeCount>,multiParticipantCalls:int,followUp:FollowUp}
 * @phpstan-type Segment array{dimension:'message_type'|'text_band'|'origin'|'calling_code'|'customer_devices',key:string,sendAttempts:int,sent:int,sendFailures:int,sendFailureRate:int|float|null,completedConversations:int,deliveredConversations:int,readConversations:int,repliedConversations:int,deliveryRate:int|float|null,readRate:int|float|null,replyRate:int|float|null,averageCustomerReplyMs:int|float|null,readRateInterval95:array{int|float,int|float}|null,replyRateInterval95:array{int|float,int|float}|null,readRateDifference:int|float|null,replyRateDifference:int|float|null,shareOfConversations:int|float|null,shareOfSends:int|float|null}
 * @phpstan-type Engagement array{windowHours:24,completedConversations:int,deliveredConversations:int,readConversations:int,repliedConversations:int,deliveryRate:int|float|null,readRate:int|float|null,replyRate:int|float|null,averageCustomerReplyMs:int|float|null,complete:bool,droppedConversations:int,droppedRecords:int,droppedReceiptJoins:int}
 * @phpstan-type Platform 'web'|'android'|'iphone'|'ipad'|'macos'|'windows'|'wearable'|'ar_device'|'unknown'
 * @phpstan-type RecipientDevices 'primary_only'|'one_linked'|'two_plus_linked'|'unknown'
 * @phpstan-type PlatformCount array{platform:Platform,messages:int,share:int|float|null}
 * @phpstan-type InventoryDevice array{deviceIndex:int,estimatedPlatform:Platform,reportedClass:'phone'|'desktop_app'|'browser'|'business_api'|'unknown',lastActiveAt:int|float|null,listed:?bool}
 * @phpstan-type Inventory array{listObserved:bool,listCurrent:bool,observedAt:int|float|null,deviceCount:?int,truncated:bool,devices:list<InventoryDevice>}
 * @phpstan-type Devices array{detector:'message_id_prefix/v1',measured:bool,complete:bool,observedBuckets:int,customerMessages:?int,accountMessages:?int,customerPlatforms:list<PlatformCount>,accountPlatforms:list<PlatformCount>,inventory:Inventory|null}
 * @phpstan-type ActivityRow array{ts:int|float,recipientCountry:string,recipientDeviceCount:RecipientDevices,deviceSource:'primary'|'linked'|'unknown',incomingMessages:int,deliveryReceipts:int,readReceipts:int,onlineSignals:int,offlineSignals:int,typingSignals:int,lastSignalAt:int|float,quietGaps:int,quietGapMs:int|float,averageQuietGapMs:int|float|null}
 * @phpstan-type RecipientActivity array{measured:bool,complete:bool,observedBuckets:int,droppedSignals:int,truncated:bool,rows:list<ActivityRow>}
 * @phpstan-type ConversationGroup array{ts:int|float,messageType:'text'|'image'|'video'|'audio'|'document'|'sticker'|'interactive'|'template'|'other',textBand:'none'|'short'|'medium'|'long'|'very_long'|'unknown',origin:'api'|'campaign'|'other',callingCode:string,customerDevices:'single'|'multiple'|'unknown',completedConversations:int,deliveredConversations:int,readConversations:int,repliedConversations:int,replyLatencySumMs:int|float,readRate:int|float|null,replyRate:int|float|null,averageCustomerReplyMs:int|float|null,recipientCountry?:string,recipientDeviceCount?:RecipientDevices}
 * @phpstan-type Breakdown array{measured:bool,complete:bool,observedBuckets:int,droppedConversations:int,truncated:bool,buckets:list<array{ts:int|float,complete:bool}>,rows:list<ConversationGroup>}
 * @phpstan-type MessageAnalysis array{complete:bool,segments:list<Segment>}
 * @phpstan-type CustomerActivity array{observed:bool,onlineSignals:int,offlineSignals:int,typingSignals:int}
 * @phpstan-type AccountActivity array{observed:bool,primaryPhoneActivitySignals:int,primaryPhoneActivePeriods:int,completedPhoneActivityPeriods:int,phoneActivityMs:int|float,averagePhoneActivityMs:int|float|null,phoneQuietGaps:int,phoneQuietMs:int|float,averagePhoneQuietMs:int|float|null,primaryPhoneMessages:int,otherDeviceMessages:int,primaryPhoneReplies:int,otherDeviceReplies:int,averagePrimaryPhoneResponseMs:int|float|null,averageOtherDeviceResponseMs:int|float|null,lastPrimaryPhoneAt:int|float|null}
 * @phpstan-type ResponseQueue array{awaitingReply:int,oldestWaitingMs:int|float,observedAt:int|float,complete:bool}
 * @phpstan-type Metrics array{measured:bool,observedHours:int,lastObservedAt:int|float|null,outgoingMessages:int,incomingMessages:int,sendAttempts:int,sendFailures:int,sendFailureRate:int|float|null,businessReplies:int,averageBusinessResponseMs:int|float|null,onlineMs:int|float,disconnects:int,connectFailures:int,streamErrors:int,keepaliveTimeouts:int,engagement:Engagement,messageAnalysis:MessageAnalysis,customerActivity:CustomerActivity,accountActivity:AccountActivity,responseQueue:ResponseQueue|null,deviceAnalytics:Devices,recipientActivity?:RecipientActivity,conversationBreakdown:Breakdown,calls:Calls}
 * @phpstan-type Summary array{totalNumbers:int,measuredNumbers:int,connectedNumbers:int,measured:bool,observedHours:int,lastObservedAt:int|float|null,outgoingMessages:int,incomingMessages:int,sendAttempts:int,sendFailures:int,sendFailureRate:int|float|null,businessReplies:int,averageBusinessResponseMs:int|float|null,onlineMs:int|float,disconnects:int,connectFailures:int,streamErrors:int,keepaliveTimeouts:int,engagement:Engagement,messageAnalysis:MessageAnalysis,customerActivity:CustomerActivity,accountActivity:AccountActivity,responseQueue:ResponseQueue|null,deviceAnalytics:Devices,recipientActivity?:RecipientActivity,conversationBreakdown:Breakdown,calls:Calls}
 * @phpstan-type NumberMetrics array{sessionId:string,projectId:string,projectName:string,name:string,backend:string,status:string,measured:bool,observedHours:int,lastObservedAt:int|float|null,outgoingMessages:int,incomingMessages:int,sendAttempts:int,sendFailures:int,sendFailureRate:int|float|null,businessReplies:int,averageBusinessResponseMs:int|float|null,onlineMs:int|float,disconnects:int,connectFailures:int,streamErrors:int,keepaliveTimeouts:int,engagement:Engagement,messageAnalysis:MessageAnalysis,customerActivity:CustomerActivity,accountActivity:AccountActivity,responseQueue:ResponseQueue|null,deviceAnalytics:Devices,recipientActivity?:RecipientActivity,conversationBreakdown:Breakdown,calls:Calls}
 * @phpstan-type CallSeries array{sessionId:string,ts:int|float,total:int,answered:int,missed:int,declined:int,failed:int,ringing:int,answerRate:int|float|null,talkSeconds:int|float,timedAnswered:int,timedPickup:int,averageTalkSeconds:int|float|null,medianTalkSeconds:int|float|null,p95TalkSeconds:int|float|null,averagePickupMs:int|float|null,p95PickupMs:int|float|null,shortAnswered:int,video:int}
 * @phpstan-type Series array{sessionId:string,ts:int|float,outgoingMessages:int,incomingMessages:int,sendFailures:int,businessReplies:int,averageBusinessResponseMs:int|float|null,onlineMs:int|float,disconnects:int,customerOnlineSignals:int,customerTypingSignals:int,primaryPhoneMessages:int,otherDeviceMessages:int,primaryPhoneReplies:int,phoneActivePeriods:int,completedPhoneActivityPeriods:int,phoneActivityMs:int|float,phoneQuietGaps:int,phoneQuietMs:int|float}
 * @phpstan-type Analytics array{enabled:bool,period:array{start:int|float,end:int|float},requestVitals:array{requests:int,failures:int,errorRate:int|float|null},summary:Summary|null,numbers:list<NumberMetrics>,series:list<Series>,callSeries:list<CallSeries>}
 * @phpstan-type Params array{projectId?:string,sessionId?:string,start?:int,end?:int}
 * @phpstan-type MetricsParams array{projectId?:string,sessionId?:string,windowHours?:int,segments?:bool,format?:'prometheus'|'openmetrics'}
 */
final class AnalyticsModels
{
    private function __construct()
    {
    }
}
